### ISSUE TITLE
Detect and add back exotic .show() and .hide() logic

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-migrate#102]
https://github.com/jquery/jquery/pull/2180

We should only be spewing warnings for the cases that changed or make no sense, such as

* Trying to `.show()` a detached element
* Using `.show()` on an element that is cascade-hidden (let's assume it's okay to always complain about this)

**Comment by Mottie** [comment]
I would like to suggest adding a boolean (e.g. `.show(true)`) to mimic the current behavior and show cascade-hidden elements. A named option would also be required if the developer is using an object. Sadly, this idea would not work with `.toggle()`.

**Comment by markelog** [comment]
Have to recuse myself, can't find the time

**Comment by dmethvin** [comment]
Since we did a much less extreme change in 3.0 and haven't had problems reported, I'll close this.
