### ISSUE TITLE
Restore :visible and :hidden definitions

### ISSUE THREAD

**Issue by gibson042** [jquery/jquery-migrate#107]
jquery/jquery/issues/2227

Migrate will need to reinstate the old `:hidden` & `:visible` pseudos, and warn about discrepancies (elements with layout boxes but no width and no height).

**Comment by dmethvin** [comment]
I wonder, is this a common enough problem that we should shim it?

**Comment by dmethvin** [comment]
I'm going to close this as being rare, but if we get enough reports after 3.0 ships we can add it to the 3.0 Migrate.
