### ISSUE TITLE
Shim old easing parameters and provide a warning.

### ISSUE THREAD

**Issue by gnarf** [jquery/jquery-migrate#111]
https://github.com/jquery/jquery/pull/2376 from @Mr21 is going to be removing the "extra parameters" that have been passed to easing.  We need to put a shim in place that can detect the arity of a easing function being >1 argument and provide a warning / shim the additional parameters back in.

**Comment by dmethvin** [comment]
Is this a common enough situation that it needs to be shimmed? Do we know of specific code that is depending on the extra parameters?

**Comment by gnarf** [comment]
the shim is like ~1 line of code? only needed in the "debug build" ?

**Comment by dmethvin** [comment]
Nothing in old jQuery versions uses the params? If it does I'd be concerned about noise that the user wouldn't understand.

**Comment by scottgonzalez** [comment]
> Do we know of specific code that is depending on the extra parameters?

The [easing plugin](http://gsgd.co.uk/sandbox/jquery/easing/), which is still the #1 result on Google for "jquery easing".

**Comment by gnarf** [comment]
Nothing in old jQuery UI or jQuery uses it for a few versions back

**Comment by gnarf** [comment]
I also think it wont be very "noisy" - once per custom easing function that still uses the extra parameters

**Comment by Mr21** [comment]
I already search where this parameters is used, and I didn't find anything, even after the first commit of jquery, these parameters is useless :(

But I send another mail to the author of the jquery easing plugin, to upgrade it.

**Comment by scottgonzalez** [comment]
Honestly, if a new version of that plugin is going to come out, it will be so different from the current version that it should just be deprecated in favor of jQuery UI's easings. We've already done the work of optimizing for size.

**Comment by Mr21** [comment]
Yep, I saw your code, I like the way how it's written :)
But, maybe we can just do a copy/past of your version inside the plugin and that's it.
So, after that, the #1 result on google will not be a problem anymore, right?

**Comment by scottgonzalez** [comment]
While you have the legal right to do so (with the copyright and license terms staying in tact), there is really no reason to do that. How is that in any way better than pointing people to the original code?

Note that before the next jQuery UI release, easings will be in their own file.

**Comment by Mr21** [comment]
> there is really no reason to do that.

hmm, it's for the next users maybe, you said yourself when we search `jquery easing` on google, the first result is the plugin. So I thought the solution was to update the plugin directly.
I read in the jquery-ui file the original idea is from the plugin, so I believe in the fact you can do the same in return?

It's only a proposition, if you show me it's a bad move, I will not do it, but I not understand exactly why is not _the_ good solution :(

**Comment by scottgonzalez** [comment]
> hmm, it's for the next users maybe, you said yourself when we search jquery easing on google, the first result is the plugin. So I thought the solution was to update the plugin directly.

Or just ask the author to put a big notice on the page that says to use jQuery UI's easings.

> I read in the jquery-ui file the original idea is from the plugin, so I believe in the fact you can do the same in return?

I'm not sure what you mean by this. We have an optimized version of all the easings. You'll be able to get them by themselves, with no dependencies other than jQuery. What is the benefit of pointing people to the old easing plugin? Where would that notice go? In what scenario is this beneficial for users?

> It's only a proposition, if you show me it's a bad move, I will not do it, but I not understand exactly why is not the good solution :(

How is replacing 100% of the code in the easing plugin with a copy/paste from jQuery UI a good solution?

**Comment by Mr21** [comment]
> How is replacing 100% of the code in the easing plugin with a copy/paste from jQuery UI a good solution?

Only to fix theproblem of the google's result. But I admit the notice on the page is another solution, yep, why not.

**Comment by dmethvin** [comment]
The problem we've historically tried to solve with Migrate is that people attempt to upgrade their jQuery core, but don't realize they need to upgrade several other dependencies or change their own code and things mysteriously break. Where possible, and it's usually possible, we both shim the now-broken functionality and give a warning about the fix that needs to be done. The warning should be clear and give the most likely causes. 

So in this case it seems like the most commonly encountered situation by far will be someone using the old jQuery Easing plugin. If it's the first result on Google you can bet people are still using it and it would help them to get a warning. We'll need to punch `.animate()` to look at the function arity and wrap with a new function if it expects the old-style calling sequence, saving `duration` so we can reconstitute the old args at call time?  Or am I over-thinking this?

**Comment by scottgonzalez** [comment]
I don't think you're over-thinking this; what you've described is how I would handle it. Handling it directly in `.animate()` means that direct uses of `Tween` will be missed, but I think anyone use `Tween` probably isn't using Migrate.

**Comment by gnarf** [comment]
Sorry, my original thought on approach is not as short as it really will be.  

I think the path we would want to take, detect an easing function with airty during a $.Animaiton.prefilter(), warn about the specific easing function (once only), and then override `jQuery.Tween.prototype.run`, with the current code:

```js
	jQuery.Tween.prototype.run = function( percent ) {
		var eased,
			hooks = Tween.propHooks[ this.prop ];

		if ( this.options.duration ) {
			this.pos = eased = jQuery.easing[ this.easing ](
				percent, this.options.duration * percent, 0, 1, this.options.duration
			);
		} else {
			this.pos = eased = percent;
		}
		this.now = ( this.end - this.start ) * eased + this.start;

		if ( this.options.step ) {
			this.options.step.call( this.elem, this.now, this );
		}

		if ( hooks && hooks.set ) {
			hooks.set( this );
		} else {
			Tween.propHooks._default.set( this );
		}
		return this;
	};
```

Alternatively, we could refactor the version of run that will be shipped in the next version to make the "easing" call abstracted into Tween.prototype.ease( percent ) which we could then back-compat a lot easier (one or two line change vs whole function) -- something like
```js

Tween.prototype.ease = function( percent ) {
  if (this.options.duration) {
    return jQuery.easing[ this.easing ]( percent );
  }
  return percent;
}
```

and then we can make that weird if with the easings just this.pos = this.ease( percent );

**Comment by markelog** [comment]
I found a lot of code that depend on such behaviour, i think we need to fix this ticket before releasing final and also document it in the final blog post (/cc @timmywil).

I can take this in, to expedite this process.

**Comment by mgol** [comment]
@dmethvin @markelog I'm confused, is the current `master` branch targetted at Migrate 3, 2 or 1? The commit fixing this issue should only go to 3.0.0 but current `master` is tested on the same browsers jQuery 1 supports.

**Comment by mgol** [comment]
Same applies to the fact that current `master` is tested against all jQueries from 1.6 to 2.2 which is not the plan for Migrate 3.0.0.

**Comment by dmethvin** [comment]
We at least need to put out 1.3.1 to fix a couple of bugs fixed recently, and knowing luck there will need to be a 1.3.2 at some point. We'll need to split this and run two tests, one for a new 1.x-stable branch and the other for master. Is that something you'd be able to do?

**Comment by mgol** [comment]
Sure, I can do it; does branching `1.3-stable` at the commit from just before @markelog's commits sound fine? I'll then update the Jenkins jobs.

I can do it this weekend.

**Comment by dmethvin** [comment]
Yeah that would be great. We can cherry pick the fixes into that when they're ready. Thanks!

**Comment by markelog** [comment]
Yeah, we can do that, but if warning will show up for earlier jQuery versions, that wouldn't be end of the world, or might be even preferable for some users

**Comment by mgol** [comment]
Semver doesn't allow to deprecate stuff in a patch release so we'd have to release 1.4.0. It's probably better to leave it as it is on 1.x.

**Comment by markelog** [comment]
We don't deprecate any functionality of the jquery-migrate itself, semver doesn't regulates versioning of dependant packages, so that rule couldn't be applied here.

**Comment by mgol** [comment]
It might be that formally nothing in the semver spec prevents us from doing that but, still, adding warnings is a potential for introducing failures. Other code may depend on certain methods not causing warnings (they may e.g. checking it in CI) etc. I think it's in good taste to not introduce such changes in patch releases.

**Comment by markelog** [comment]
> Other code may depend on certain methods not causing warnings (they may e.g. checking it in CI) etc

That would be interesting, by that i mean - weird and by that i mean - really? People do that? Would love to see some example.

> I think it's in good taste to not introduce such changes in patch releases.

I'd say, it could be better to notify user about potential harm code as the early as possible.

**Comment by dmethvin** [comment]
I could definitely see someone's CI saying, "If warnings are reported on the console then the test fails." If we're putting out 1.3.1 I don't think we'd want to add more warnings there since it should just be bug fixes and we have a few of those. We could add new warnings in a 1.4.0 though. That would imply that the branch should be something like `1.x-stable` I guess?

**Comment by mgol** [comment]
@dmethvin It can be `1.x-stable` for me, I don't care too much if we're releasing 1.3.1 or 1.4.0, I just strongly think we shouldn't introduce console warnings in patch releases with exception of cases where they were meant to be there but were not getting fired because of a Migrate bug.

**Comment by markelog** [comment]
> "If warnings are reported on the console then the test fails."

I'm wondering about the use-case for that, can't think of any situation when anyone would add that sort of thing.

> I don't think we'd want to add more warnings there since it should just be bug fixes and we have a few of those.

We can consider this as new functionality, then it should be a minor. But in any case, that sounds as a bikeshedding to me, i don't think anyone would complain in either of situations, we just being perfectionists i guess.

**Comment by mgol** [comment]
>> "If warnings are reported on the console then the test fails."
>
> I'm wondering about the use-case for that, can't think of any situation when anyone would add that sort of thing.

E.g. someone needs to use Migrate until all problems are fixed but they want to make sure no new warnings are introduced to the code base (so that the migration doesn't regress) so they make CI break on warnings in already migrated scenario.

**Comment by markelog** [comment]
Interesting! if you know what i mean :)
