### ISSUE TITLE
Round .css('width'/'height')

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-migrate#112]
https://github.com/jquery/jquery/issues/1724 will change the output of `.css('width')`, `.css('height')` and other methods like `.width()` to return fractional values. Migrate should round them.

**Comment by mzgol** [comment]
@dmethvin do we have a milestone for issues that need to be resolved for the Migrate release that's going to come out with jQuery 3.0.0?

**Comment by dmethvin** [comment]
Just created one.

**Comment by dmethvin** [comment]
On this item, we can definitely round all the results unconditionally for backcompat. I am wondering when we should actually issue a warning though. The results can be fractional only on specific browsers and platforms.

I am thinking that always issuing a warning on the first `.width()` and `.height()` will be very noisy and perhaps give false alarms, so I'd prefer to only give a warning if the original result is fractional. There we still risk the chance that some fractional result may occur on a platform not tested but false alarms tend to annoy people a lot more.

Also, this affects the inner/outer variants as well. I am inclined to give a warning once for each new API that returns a fractional number that we round. Other dimensions we get via `window.getComputedStyle()`, such as `border-right-width` already can return fractions that we don't round, so we don't need warnings for other `.css()` results.

**Comment by mzgol** [comment]
I'm not sure about those warnings. When a dev has a div with `width: 33.3px` and uses `elem.css('width')`, they may not care whether the dimensions are fractional or not, they just use what they have. Issuing a warning there would be confusing...

OTH, I don't see a lot of other ways of letting the developer know that something changed here. If we want a warning, limiting it to one occurrence for a method (or one occurrence at all) seems like a good idea.

**Comment by dmethvin** [comment]
Thinking about this a bit more, I can see it becoming really annoying. Most of our existing warnings actually require someone to take an action, this one will complain for no reason in many cases. So I'm inclined to not do anything here unless we get reports that indicate we need it to fix compat with some popular plugin.

**Comment by mzgol** [comment]
In that case I wonder if Migrate should do anything here. As far as I understand, the main Migrate idea is to:
1. Have a site with an old jQuery (like 1.6).
2. Add jQuery Migrate to it.
3. Fix some issues related to warnings.
4. Swap the old jQuery for the newest one.
5. Fix more issues.
6. Remove Migrate.

Would having Migrate round the values help in any of these steps?

**Comment by dmethvin** [comment]
Probably not that big of a help. Only plain `.width()` and `.height()` are guaranteed to be integers because for the outer/inner variants the "extra" may be fractional and we don't round them.

**Comment by gibson042** [comment]
> In that case I wonder if Migrate should do anything here. As far as I understand, the main Migrate idea is to:
1. Have a site with an old jQuery (like 1.6).
2. Add jQuery Migrate to it.
3. Fix some issues related to warnings.
4. Swap the old jQuery for the newest one.
5. Fix more issues.
6. Remove Migrate.

Not that it changes the argument here, but I'm expecting users to add both the new jQuery and the corresponding Migrate that emulates the previous version _atomically_ (i.e., a single step for 2–4).

**Comment by mgol** [comment]
In light of https://github.com/jquery/jquery-migrate/issues/112#issuecomment-122707557, should we do it at all?

**Comment by dmethvin** [comment]
Let's skip this.
