### ISSUE TITLE
Arguments were lost in global Ajax event

### ISSUE THREAD

**Issue by g7015412-trbvm-com** [jquery/jquery-migrate#113]
I confirmed that 
```
$(document).ajaxSend(function(a,b,c){
   // b and c are undefined!!
});
```
In pure jQuery, **b** is jqXHR, and **c** is ajax option.

Is it correct action of this library?

I know why it occurred.
In Line 120 of event.js
```
jQuery.event.trigger( name, null, elem, true );
```
Second argument is specified **null**.
It works same as pure jQuery, if second and subsequent elements of arguments was passed to.
```
jQuery.event.trigger( name, [].slice.call(arguments,1), elem, true );
```

Upper code makes good results for me, but it may make other bugs.
So, I didn't fix it.

Is it a bug?

**Comment by dmethvin** [comment]
Can you provide a test case? There probably is a bug here but it would help to a complete example.

**Comment by g7015412-trbvm-com** [comment]
Sorry, previous example has mistake.

## Good case
```
<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.2.1/jquery-migrate.min.js"></script>

<script>
$(function(){
	$(document).ajaxSend(function(ev, jqxhr, ajaxOpts){
		console.log(ev, jqxhr, ajaxOpts);
		// m.Event, Object, Object
	})
	
	$.ajax("sample.txt")
});
</script>
```
In this case, **jqxhr** and **ajaxOpts** are available.


## Bad case
```
<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.2.1/jquery-migrate.min.js"></script>

<script>
$(function(){
	$("body").ajaxSend(function(ev, jqxhr, ajaxOpts){
		console.log(ev, jqxhr, ajaxOpts);
		// m.Event, undefined, undefined
	})
	
	$.ajax("sample.txt")
});
</script>
```
In this case, **jqxhr** and **ajaxOpts** are undefined.

The problem seem to occur when selector doesn't specify **document**.

**Comment by dmethvin** [comment]
Thanks, I'll take a look.
