### ISSUE TITLE
'$.attr' returns undefined for boolean inputs even if they are in attribute list

### ISSUE THREAD

**Issue by iabw** [jquery/jquery-migrate#116]
This is pretty minor, but it's an actual bug in production for us, and I couldn't find any issues that seemed to cover this.

##### Overview

jQuery migrate causes `$.attr` to return undefined for boolean attributes if the requested boolean's property is false, even if the attribute is not. I am experiencing this problem because Firefox is incorrectly giving a checkbox input a property of `checked: false` on a live site. This is causing jQuery migrate to make `$el.attr('checked')` return `false`, although it should be returning `"checked"` because "checked=checked" is still in the attributes list.

##### Versions

This is using jQuery version 1.11.2 and jQuery migrate 1.2.1, although I believe the versions are irrelevant.

##### Simple Reproduction

Make a checkbox element that is checked, then set it's checked property to false. Then try to get its checked attribute and it will return undefined.
```
var $input = $('<input id="shippingIsBilling" name="shippingIsBilling" checked="checked" class="js-shippingIsBilling" type="checkbox">').appendTo('body')
$input.get(0).checked = false;
$input.get(0).outerHTML
// "<input id="shippingIsBilling" name="shippingIsBilling" checked="checked" class="js-shippingIsBilling" type="checkbox">"
$input.attr('checked')
// undefined
$input.prop('checked')
// false
```

##### Why it's a bug

jQuery without the migrate plugin returns "checked" for `$input.attr('checked')`. However, the logic for the migrate plugin forces boolean attributes to agree with `$.prop` in order to return true - https://github.com/jquery/jquery-migrate/blob/master/src/attributes.js#L46

##### Proposed Solution

I think that if an item is in the attributes list, it should probably return that from a `$.attr` call, instead of short-circuiting to a ( in this case, incorrect ) call to `prop`.

##### Live Reproduction

I'm only actually experiencing this problem in Firefox ( I'm on version 40.0.3, but also experienced it in 40.0.2 ). It works as expected in Chrome 44.0.2403.157.

This bug should be able to be recreated on https://www.smartdestinations.com/checkout/sdi-checkout.ep . You'll need to [add an item to your cart](http://www.smartdestinations.com/pass.ep?filters=_d_Bos_Prod_Go) first. Then, go to checkout but don't do anything. You should see 3 delivery options. Refresh the page. If all went right ( wrong? ), you should now see 5 delivery options, and can explore the bug.

You can now run the following snippets in the console:

```
$(".js-shippingIsBilling").get(0).outerHTML
// "<input id="shippingIsBilling" name="shippingIsBilling" checked="checked" class="js-shippingIsBilling" type="checkbox">"
$(".js-shippingIsBilling").attr('checked')
// undefined
$(".js-shippingIsBilling").prop('checked')
// false
```

jQuery without the migrate plugin returns "checked" for `$(".js-shippingIsBilling").attr('checked')`. I tested locally that this is true - there's not a public version of the page without the migrate plugin.

I believe this is some kind of bug in Firefox caching input values, although the input is never being set to false, so that doesn't REALLY make sense.

I think Firefox should stop doing whatever it's doing that's messing this up, and if it did, I wouldn't care about this "bug" being fixed in jQuery migrate. I'm not sure how to describe it any more clearly than this report, so I'll probably just link this in bugzilla, if it will let me.

**Comment by dmethvin** [comment]
> jQuery without the migrate plugin returns "checked" for $input.attr('checked'). However, the logic for the migrate plugin forces boolean attributes to agree with $.prop in order to return true

Yes, this is an edge case where providing backwards compatibility means that Migrate re-introduces behavior that may not be desirable. The solution is to make it so that your code doesn't require Migrate for long-term use.  Although Migrate *can* be used to shim in the old behavior, there are cases like this that will arise. That is one reason we only advise it be used for developers to find and fix the bugs.

Out of curiosity, how is this manifesting as a bug in your code? Are you looking at attributes and not properties?

**Comment by iabw** [comment]
> How is this manifesting as a bug in your code?

I was trying to look at the `checked` property of a checkbox input. However, Firefox is incorrectly giving the input a property of `checked: false` after the page loads, so I tried to use the attribute instead and ran into this.

As you said, the migrate plugin shouldn't really be in production anyway, it just hasn't been a priority for us to finish the process. I'm completely fine with this being closed if it's not a "real" bug.

**Comment by dmethvin** [comment]
Thanks for reporting the bug. I've left it open for a while but think that it's pretty rare. If someone would like to try and tackle it we could review a PR.
