### ISSUE TITLE
removeAttr( boolean ) no longer sets the property to false

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery-migrate#118]
https://github.com/jquery/jquery/issues/1759

**Comment by timmywil** [comment]
An example of a behavior change is that `.removeAttr("checked")` will no longer uncheck the checkbox.

**Comment by dmethvin** [comment]
Migrate can't know whether that behavior was intended by removing the attribute, but for HTML documents it's so rare to need to `.removeAttr("checked")` that it's almost certainly a confusion about attributes versus properties. So we might as well warn when we see it, and the docs can mention that if you *really* meant to do that you can ignore the warning.

**Comment by dmethvin** [comment]
The jQuery Core commit is the one causing fails in the Migrate unit tests. With this one it's difficult to determine intent based on the call, so I'm trying to determine whether to just warn about this or if we actually have to shim the old behavior which varies from 1.x/2.x because of oldIE.

**Comment by dmethvin** [comment]
I'll take this one
