### ISSUE TITLE
jQuery 1.12.0: Cannot read property 'opener' of null

### ISSUE THREAD

**Issue by ocean90** [jquery/jquery-migrate#128]
With jQuery 1.12.0, jQuery Migrate 1.2.1 and jQuery UI 1.11.4 I get an "Uncaught TypeError: Cannot read property 'opener' of null" error at https://github.com/jquery/jquery/blob/1.12.0/src/css/curCSS.js#L22

You should get the same error with this JSFiddle: https://jsfiddle.net/7unv8rrm/2/

(The next jQuery UI version doesn't have the mentioned line anymore, see https://github.com/jquery/jquery-ui/commit/c077e0a347826c7acca4ca2f775ca59e3b5f8d07#diff-9642379d08d860be4c2831b0ff5b9a85.)

**Comment by timmywil** [comment]
Thanks for opening an issue. Could you try the git version of migrate?

**Comment by ocean90** [comment]
Yep sure, https://jsfiddle.net/7unv8rrm/3/ is using https://code.jquery.com/jquery-migrate-git.js, the error persists.

**Comment by dmethvin** [comment]
Thanks! Looks like we need to make the elements owned by `document` if nobody else claims them.

**Comment by ocean90** [comment]
@dmethvin thanks for the fix, it's working for me.

I noticed this issue while updating [jQuery for WordPress](https://core.trac.wordpress.org/ticket/35380). Is there already a schedule for a new release? The next WordPress release is planned for [April 12th](https://make.wordpress.org/core/version-4-5-project-schedule/), so it doesn't need to be right now.
I'm thinking about including the git version during the alpha and beta phase so it can be tested by a bigger audience. Thoughts?

**Comment by dmethvin** [comment]
Yes, we'll be putting out a new release in a day or two so  you'll be able to include that production version. Much appreciated!

**Comment by dmethvin** [comment]
http://blog.jquery.com/2016/01/13/jquery-migrate-1-3-0-released/
