### ISSUE TITLE
Convert to QUnit 2.0 style

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-migrate#129]
The new QUnit style is cleaner, it should be pretty easy to convert since it's just a case of following the same pattern as the main jQuery tests and updating the QUnit dependency.

**Comment by dmethvin** [comment]
Still need to convert `expectWarning()` and `expectNoWarning()`, seems like they might be done as QUnit plugins.

**Comment by aa533aa** [comment]
Help me

**Comment by dmethvin** [comment]
Actually I'm okay with these two test methods being globals, but if someone wants to implement as QUnit plugins feel free to submit a pull request.
