### ISSUE TITLE
Latest stable 1.2.1 will not more work with jQuery 2.2.0

### ISSUE THREAD

**Issue by neralex** [jquery/jquery-migrate#130]
As the topic says, jquery-migrate-1.2.1 will not more work jQuery 2.2.0 but your pre-version of jquery-migrate-1.2.2 works.

**Comment by mgol** [comment]
We will release a Migrate version that works with jQuery 2.2/1.12 soon. Thank you for your patience!

**Comment by dmethvin** [comment]
http://blog.jquery.com/2016/01/13/jquery-migrate-1-3-0-released/
