### ISSUE TITLE
Release script fails on `npm publish` (Windows, msysgit)

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-migrate#131]
Not sure why but it doesn't seem to be able to find the `npm` command. Running `npm` from the command line works fine. I had to finish the 1.3.0 release manually.

**Comment by mgol** [comment]
That would indicate the script sees a different `PATH` than what you have in the console.

**Comment by dmethvin** [comment]
Yeah, I just have to track it down before the next release so I created an issue to avoid forgetting.
