### ISSUE TITLE
FALSE Warn on ready event

### ISSUE THREAD

**Issue by roborobo2** [jquery/jquery-migrate#137]
jquery migrate plugin 1.3.0 give me false ready event warning because I use "ready.jstree" not just "ready".
see example
http://jsfiddle.net/3q9Ma/582/

**Comment by dmethvin** [comment]
That's not how event namespaces should be used. if the event relates to the readiness of the plugin itself, it should be named something like `jstree:ready` or `jstreeready`. However, I think we can probably avoid this by checking the element, given that this plugin already exists and is abusing the name.
