### ISSUE TITLE
Warn about unqoted attribute selectors containing #

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-migrate#140]
We've removed unofficial "support" for selectors with unquoted attribute values where it has to be quoted, like `a[href=#]` in jQuery 2.2.0/1.12.0. It turns out many people relied on that as we get a lot of bug reports about this change.

Migrate should warn about it.

**Comment by mgol** [comment]
Bug reports about this:

1. https://github.com/jquery/jquery/issues/2811
1. https://github.com/jquery/jquery/issues/2824
1. https://github.com/jquery/jquery/issues/2829
1. https://github.com/jquery/jquery/issues/2876
1. https://github.com/jquery/jquery/issues/2884
1. https://github.com/jquery/jquery/issues/2885

**Comment by timmywil** [comment]
The changes only affected unquoted attribute values containing hashes. All other unquoted attribute values work the same way.

**Comment by dmethvin** [comment]
Fixed in 5770782bfef76e92cecfd54c8cda41043b82ffcd
