### ISSUE TITLE
Always console.warn or console.error when migrate is included

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery-migrate#149]
To deter people from including migrate in production.

"Please remove migrate in production"

**Comment by markelog** [comment]
I think we need to warn about this new thing in the blog post or in the tweet. Also mention that use of the migrate might impact their perf

**Comment by mgol** [comment]
I'd like this warning to be included in the minified version as well.
Otherwise we'll never stop the Migrate abuse on WordPress sites and the
like.

-- 
Michał Gołębiowski
