### ISSUE TITLE
Remove the code from jQuery versions older than 1.12/2.2

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-migrate#152]
Since Migrate 3.0 is supposed to work only with jQuery 1.12/2.2, it shouldn't restore behavior not present in these versions, e.g. `jQuery.browser`, `jQuery.support.boxModel`, `jQuery.sub` & others.

**Comment by dmethvin** [comment]
Yes, agreed that a lot of the older functionality should be removed. Nobody using jQuery 3.0 should also be using `jQuery.browser`! Basically #120 is about updating the README to explain how someone would get, say, from 1.9.1 to 3.0.0.

I think we agreed it would be a two-step process where someone would run with Migrate 1.4.0 (or later), fix problems, then use Migrate 3.0.0. 

I think we specifically wanted to avoid having people "stack" Migrates to get things working. :smile_cat:

**Comment by mgol** [comment]
PR: #155. Review appreciated.
