### ISSUE TITLE
Is version 1.4.0 already released?

### ISSUE THREAD

**Issue by ocean90** [jquery/jquery-migrate#159]
I just noticed a 1.4.0 tag which was created 26 days ago in 4df78fbf89a9d70e54d476c4b49bc83b043b62ea. But I couldn't find a release post on http://blog.jquery.com/.

https://github.com/jquery/jquery-migrate#development-version also still mentions 1.3.0 while https://github.com/jquery/jquery-migrate/tree/1.x-stable#development-version links to 1.4.0.

**Comment by ocean90** [comment]
Based on the version of https://www.npmjs.com/package/jquery-migrate it looks like it is.

**Comment by mgol** [comment]
It's been released, yes. We don't necessarily have to announce every minor update of the Migrate package on the blog but it might have been oversight. @dmethvin, was it on purpose?

**Comment by dmethvin** [comment]
Now that we're publishing on npm it didn't seem necessary to make a blog post for every minor release. We'll announce Migrate 3.0 though since it coincides with a new jQuery major release.
