### ISSUE TITLE
The AUTHORS.txt file is outdated

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-migrate#193]
The AUTHORS.txt file is outdated, both on `master` & `1.x-stable`.

I see there is a Grunt task called `authors` but it just prints a list. How do we update it file? @dmethvin?

**Comment by dmethvin** [comment]
It's described generally in the [Release Process](https://github.com/jquery/jquery/wiki/Release-process) wiki page. Run `grunt authors` and there will be names at the bottom not in the file yet, just add them in a commit. Sometimes the author will have signed with a different name or email and is already in the file, when you know that is true you can add an entry to `.mailmap` and update the information for the *first* reference to be the most current.

**Comment by mgol** [comment]
Thanks! I updated the file.

**Comment by mgol** [comment]
Thanks! I updated the file on `master` & `1.x-stable` & added the `.mailmap`.

**Comment by dmethvin** [comment]
Much appreciated!
