### ISSUE TITLE
Hosted migration file returning 404

### ISSUE THREAD

**Issue by jordandh** [jquery/jquery-migrate#194]
README.md says to use https://code.jquery.com/jquery-migrate-3.0.0.js but it is returning 404

**Comment by dmethvin** [comment]
Yeah, we haven't released it yet so at the moment it's a placeholder. The release script will update it so I can patch it manually. . The path for the release candidate is mentioned on the blog, http://blog.jquery.com/2016/05/20/jquery-3-0-release-candidate-released/

**Comment by jordandh** [comment]
Ok, thanks. I was following the upgrade guide which does not mention the rc release.

**Comment by dmethvin** [comment]
README is fixed by 94d9800a9b0694be55cba971ccccc673d2555f6c thanks!

**Comment by jordandh** [comment]
Great :)
