### ISSUE TITLE
Fix the regexp test in release.js before 3.0 final

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-migrate#195]
I manually fixed the README for #194, right now the release script does not update that file for pre-release versions. However, the [regexp](https://github.com/jquery/jquery-migrate/blob/94d9800a9b0694be55cba971ccccc673d2555f6c/build/release.js#L247) in the release script won't recognize the URLs with prerelease versions.

**Comment by dmethvin** [comment]
To be clear, I think release.js is making the right decision here as the comment above it says, we should not update the README for beta releases. The 3.0.0 release is a bit special since we have a 1.x-stable branch separated from master. So the regexp needs to be changed so that it can recognize this special case and actually update the beta version currently in the master/3.0 README.

**Comment by mgol** [comment]
Ideally the code would update the version to the next pre-release but only if a pre-release is already present. :)

**Comment by dmethvin** [comment]
The only time I think we'd want to have a beta version in the file is when we're going to a major version that isn't the same thing as the previous major, which was the case here. Otherwise I can see people complaining that there is no link to the latest production version there. The master/3.0-to-be branch has a link to the latest 1.4.1 production version via the big message at the top but unless there's a beta version there would be no link at all related to the 3.0 candidate.

Not sure how other projects handle this, people could oh, maybe, look in npm for the version but a lot of people seem to look at the readme for it.

**Comment by mgol** [comment]
Yes, I meant that if you have `3.0.0` in README it shouldn't update to `3.1.0-rc1` but if you have `3.1.0-beta1` in README it should update to `3.1.0-rc1`.

That's not terribly important, just a nice touch. :)
