### ISSUE TITLE
Naive shim around $.data breaks much code

### ISSUE THREAD

**Issue by markrendle** [jquery/jquery-migrate#198]
The shim around .data doesn't support the same set of overloads as the core function. It assumes the second parameter is the `name` property, whereas it can be an object to set a bunch of properties simultaneously.

See: https://github.com/jquery/jquery-migrate/blob/master/src/data.js#L7
vs: https://github.com/jquery/jquery/blob/master/src/data.js

Among other things, this breaks AngularJS.

**Comment by dmethvin** [comment]
There is a difference between `jQuery.data()`, which Migrate shims, and `jQuery.fn.data()` which Migrate does not touch. Can you provide a test case that shows the problem?

**Comment by dmethvin** [comment]
Closing, but if you have some more information I can reopen.

**Comment by mgol** [comment]
This seems to be breaking Angular: https://github.com/angular/angular.js/issues/15370. Let's reconsider.

**Comment by mgol** [comment]
There is a PR for this issue at #235.

**Comment by mgol** [comment]
@markrendle Could you make sure [the development version of Migrate](https://code.jquery.com/jquery-migrate-git.js) fixes your issue?

**Comment by donpisci** [comment]
@mgol Have you any idea when you think the version with the 'string.replace is not a function' fix will be officially released?

Thanks!

**Comment by dmethvin** [comment]
@donpisci The PR was #235 and landed for the 3.0.1 release. Are you still seeing the problem with that version? If so please open a new issue and provide a test case.

**Comment by donpisci** [comment]
@dmethvin Yes, I found the 3.0.1 release shortly after leaving the message and hadn't got round to updating my message- apologies! 

All's working now.
