### ISSUE TITLE
Provide a way to filter out (or easily spot) messages triggered by jQuery UI or jQuery Mobile

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery-migrate#202]
Use case: I am using jQuery + jQueryUI + my own code depending on both, and I want to migrate to jQuery 3.

So, I'll use the jQuery Migrate plugin and look at the messages it generates pointing out migration issues.

Result: I am flooded by tons of warnings caused by jQuery UI using deprecated features. JqueryUI won't get rid of them and for a good reason, because they have to maintain bc with older jQuery versions.

Right now, the only way to distinguish between warning issued by jQuery Migrate that are triggered by my code, and hence need my attention, and those triggered by jQuery UI, which I have to ignore, is to inspect each trace one by one. That is painful and unviable.

Since there are official jQuery products out there (jQueryUI and probably jQueryMobile) that are and will keep using deprecated jQuery features, jQuery Migrate should provide a way to easily filter out or "spot" messages triggered by those product. It should recognize when a warning is caused by jQuery UI or jQuery Mobile, and there should be an option (probably enabled by default) to filter out these messages completely. Or, as a second-best alternative (actually, this would be desirable regardless of the former), the name of the file that has triggered the message should be included in the message itself instead of being buried in the trace. So, just by looking at the list of migration warning without inspecting them, you could more easily spot the ones that need attention.

**Comment by dmethvin** [comment]
> Result: I am flooded by tons of warnings caused by jQuery UI using deprecated features.

As I understood it, jQuery UI is coming out with a version that should run without warnings. If there are other plugins that are no longer maintained but are using deprecated features, you could fork and fix them.

> Right now, the only way to distinguish between warning issued by jQuery Migrate that are triggered by my code, and hence need my attention, and those triggered by jQuery UI, which I have to ignore, is to inspect each trace one by one.

How do we know the heritage of the code that is generating the error? Someone can combine their own code with other plugins into the same file, for example, and may use Uglify to process the combined file. 

I don't think there's a workable solution to do this, but if you have one feel free to make some suggestions.

**Comment by teo1978** [comment]
> How do we know the heritage of the code that is generating the error?

The same way I know when I inspect the trace: the file name is in the first line of the trace. Maybe you could provide a configurable option with a list of filenames to be filtered out.

> Someone can combine their own code with other plugins into the same file

Good point, that's one use case where filtering by filename would not be useful. However, those who are using jQuery UI as a separate file, would benefit from it.

> I don't think there's a workable solution to do this, but if you have one feel free to make some suggestions.

I made one to improve the situation that seems to me pretty straight-forward:

> the name of the file that has triggered the message should be included in the message itself instead of being buried in the trace. So, just by looking at the list of migration warning without inspecting them, you could more easily spot the ones that need attention.

This might not solve all cases, but I can't see a situation where it can do any harm.

**Comment by dmethvin** [comment]
Is this a long-term problem? @scottgonzalez is jQuery UI coming out with an update soon? The only message I was aware of was the one about `$(window).offset()`, @teo1978 are there others you've seen?

If this is a simple change please feel free to submit a pull request.

**Comment by teo1978** [comment]
> The only message I was aware of was the one about $(window).offset(), @teo1978 are there others you've seen?

Yep, at least these (besides the one you mention):

    JQMIGRATE: jQuery.expr[":"] is now jQuery.expr.pseudos
        (anonymous function)	@	jquery-ui.js:122
        (anonymous function)	@	jquery-ui.js:14
        (anonymous function)	@	jquery-ui.js:16

    JQMIGRATE: jQuery.fn.delegate() is deprecated
        datepicker_bindHover	@	jquery-ui.js:5756
        Datepicker	@	jquery-ui.js:3898
        (anonymous function)	@	jquery-ui.js:5831
        (anonymous function)	@	jquery-ui.js:14
        (anonymous function)	@	jquery-ui.js:16

    JQMIGRATE: jQuery.fn.bind() is deprecated
        (anonymous function)	@	jquery-ui.js:741
        each	@	jquery-3.0.0.js:365
        _on	@	jquery-ui.js:715
        _createWidget	@	jquery-ui.js:565
        $.(anonymous function).(anonymous function)	@	jquery-ui.js:376
        (anonymous function)	@	jquery-ui.js:531
        each	@	jquery-3.0.0.js:359
        each	@	jquery-3.0.0.js:152
        $.fn.(anonymous function)	@	jquery-ui.js:523
        (anonymous function)	@	info.php:125

The last line in the last trace is me instantiating a widget I created, but I am not using `bind()` there or anywhere else.


> @scottgonzalez is jQuery UI coming out with an update soon? 

Is that really going to make the warnings go away? Doesn't that imply that it will stop supporting old-but-not-that-old jQuery versions?

**Comment by teo1978** [comment]
> Is this a long-term problem? 

And then there's jQuery Mobile. I see that right now it doesn't even work with jQuery 3. Is it likely that an update will come any soon that won't even trigger obsolete-stuff warnings?

**Comment by dmethvin** [comment]
> Is it likely that an update will come any soon that not only will support jQuery 3 but won't even trigger obsolete-stuff warnings?

That is not a question that can be answered here.

As for this issue, as mentioned above I'm willing to accept a pull request if you think it will help the messages.

**Comment by scottgonzalez** [comment]
> @scottgonzalez is jQuery UI coming out with an update soon?

Yes, but as usual I cannot give any dates. There will be a 1.11.5 and 1.12.0 release. If you continue to use jQuery UI 1.11.x, you will for sure continue to get deprecation warnings since jQuery UI 1.11.x supports jQuery 1.6.x, which was way back before the event system changes.

> Is that really going to make the warnings go away? Doesn't that imply that it will stop supporting old-but-not-that-old jQuery versions?

jQuery UI 1.12.0 reduces support to jQuery >= 1.7.0, which is five years worth of jQuery releases, totaling over 30 different versions of jQuery Core that we support. So, no, we will not stop supporting old-but-not-that-old jQuery versions.

**Comment by dmethvin** [comment]
As I understand this ticket it reduces to "Put the file name in the warning message so I don't need to look at the stack trace". If that is the case I'd accept a PR to do that. To keep the message readable and short I think it should just be the file name part, not the full URL. The docs in warnings.md should also be updated to indicate the file name is in the message.

**Comment by teo1978** [comment]
> As I understand this ticket it reduces to "Put the file name in the warning message so I don't need to look at the stack trace". If that is the case I'd accept a PR to do that.

So why close the issue?

**Comment by dmethvin** [comment]
When you have a PR ready, just open an issue with only that description. This one went pretty far afield.

**Comment by teo1978** [comment]
Ok so I'll open a new issue. I don't see why I should  wait until I have a PR ready (which is never going to happen).
