### ISSUE TITLE
Warnings about code that will break are indistinguishable from warnings about code that just uses obsolete but working features

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery-migrate#203]
1. Try and use jQuery-UI 1.11.4 (latest stable) with jQuery3 3 and jQuery-migrate 3
=> will trigger some warnings. That's ok
2. Remove jQuery-migrate
=> everything still works (and without the warnings, of course). 

Now try this:
3. Try and use jQueryMobile 1.4.5 with jQuery3 and jQuery-migrate 3
=> will trigger warnings, similar if not identical to those at step 1
4. remove jQuery-migrate
=> code breaks, meaning it gives actual errors and stops working

jQuery UI and jQuery Mobile are just easily reproducible examples. The same can happen with user code or third party libraries.

What's wrong is that the warning are of the same kind in both cases. So, you can't tell whether:
- you are just using features that have been declared obsolete but still work (so you'd better clean up your code but it's not gonna break) OR
-  you are actually using already dead features that will break if you remove the migrate plugin.

The two situations should be produce clearly distinguishable warnings, the latter kind being more "aggressive".

**Comment by dmethvin** [comment]
This issue is too vague. In Migrate there are messages saying that some features are deprecated (may be removed in the future) and some saying that they are already removed. If the messages are unclear please open an issue saying how you'd like to see them clarified.
