### ISSUE TITLE
"jQuery.expr[":"] is now jQuery.expr.pseudos" warning: unclear whether breaking change or just deprecated

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery-migrate#204]
According to https://github.com/jquery/jquery-migrate/issues/203#issuecomment-230646733

> In Migrate there are messages saying that some features are deprecated (may be removed in the future) and some saying that they are already removed.

This warning:
```
jQuery.expr[":"] is now jQuery.expr.pseudos
```
doesn't explicitly used either the word "deprecated" or "removed". From the abovementioned comment I kind of get that if something "is now" something else it's probably a breaking change (though jQueryUI triggers this warning and doesn't break). 

Should be more explicit.

If there *are* two classes of warnings, you should use two very precise phrases with keywords that are consistently present in each of them so that they can be searched reliably, besides being 100% unambiguous.

**Comment by dmethvin** [comment]
The current wording in warnings.md says the other two methods are deprecated:

> Cause: The standard way to add new custom selectors through jQuery is jQuery.expr.pseudos. These two other aliases are deprecated, although they still work as of jQuery 3.0

Are you saying you want the word "deprecated" in the console message? How would you like it to read?
