### ISSUE TITLE
Why dist folder is in .gitignore file?

### ISSUE THREAD

**Issue by hayatbiralem** [jquery/jquery-migrate#214]
Hi,

I want to add jquery-migrate to my project with using Bower but there is no dist folder. If I want to use Bower for adding jquery-migrate, I must open its folder in terminal and install whole its dependencies then run build task.

Can you remove dist folder from .gitignore file?

Thanks.

**Comment by hayatbiralem** [comment]
Sorry, I found the answer [here](https://github.com/jquery/jquery-migrate/issues/43).

**Comment by mgol** [comment]
You can just `bower install jquery-migrate`, the package is maintained at https://github.com/appleboy/jquery-migrate (not by us).

**Comment by hayatbiralem** [comment]
Thanks @mgol, I got that ;)
