### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by vanillajonathan** [jquery/jquery-migrate#219]
It would be nice to be able to run jquery-migrate against source code and perform static code analysis to spot deprecated usage directly right in the source code as an alternative to have to use it at runtime.

It would be really cool with a website where I can just paste my JavaScript source code into a textarea and have it checked for deprecated usage.

**Comment by dmethvin** [comment]
I agree this would be a good tool. However, it would be a completely different tool than the one in this repo. Are you interested in doing a project like that? There has been interest from big jQuery users like Wordpress that have a lot of third-party themes. A static tool would let them be proactive about fixes.

**Comment by vanillajonathan** [comment]
No, I just request such a tool, I would not be interested in developing such a tool myself.

**Comment by dmethvin** [comment]
Okay, well if you know anyone with the time and expertise to build it please point them in our direction.
