### ISSUE TITLE
jquery migrate jQuery.isArray

### ISSUE THREAD

**Issue by kumarmj** [jquery/jquery-migrate#220]
Issue raised based on checklist of https://github.com/jquery/jquery/issues/2961

**Comment by dmethvin** [comment]
I had to revert the commit and reopen this, I should have realized that the previous 3.x versions still have this used internally and thus throw spurious errors. This is the same problem that would manifest in #156 and #246 if they were landed now.

We can either wait until jQuery Migrate 4.0 to land all these or add a version check and only give the warnings on later 3.x versions. Even with that, it makes the refactoring of the methods in core the critical path.

**Comment by Krinkle** [comment]
From <https://github.com/jquery/jquery-migrate/issues/246#issuecomment-287883124>
