### ISSUE TITLE
In warnings.md shows 'ready' event is deprecated but lists as $(document).ready(func); as solution that also is depricated

### ISSUE THREAD

**Issue by CommanderAlchemy** [jquery/jquery-migrate#221]
The document [Warnings.md](https://github.com/jquery/jquery-migrate/blob/master/warnings.md) have information about ready being depricated that the plugin also warns about.

But it also notes following as a solution.

``` javascript
$( document ).ready( fn )
```

Looking at [Upgrade-Guide](http://jquery.com/upgrade-guide/3.0/#deprecated-document-ready-handlers-other-than-jquery-function) It notes that the solution above is removed. I can also confirm that the migrate plugin does not warn about this.

**Comment by dmethvin** [comment]
Good point, that wording was left over from a while back before we had deprecated it. Would you like to file a pull request to change it to `$( fn )` instead?

**Comment by dmethvin** [comment]
Oh and yes there are several new deprecations that need to be added if you'd like to do some of those. There are lists at https://github.com/jquery/api.jquery.com/issues/970 and https://github.com/jquery/api.jquery.com/issues/972 .
