### ISSUE TITLE
 jQuery.parseJSON requires a valid JSON string: 204 response

### ISSUE THREAD

**Issue by senseysensor** [jquery/jquery-migrate#224]
Using flask as backend, it's impossible return anything but empty response along with status code 204. And [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5) explicitly says: 

> The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.

There is suggested solution retrieve data as text, but this seems like kludge and is ugly (IMHO). And I have number of endpoints in API with possible 204 response.

I believe jQuery / jQuery-Migrate should make exception for 204 status code and always return null for this case instead of trying parse response text.

Or I should report this in jQuery repo?

**Comment by mgol** [comment]
We already have some code to handle 204 but maybe that's not enough:
https://github.com/jquery/jquery/blob/3.1.0/src/ajax.js#L762

Could you remove Migrate and see if it's still a problem?

Also, a test case on jsfiddle or jsbin would be nice. You can use https://httpbin.org/ to mock backend responses.

**Comment by mgol** [comment]
If removing Migrate doesn't help then please move the issue to https://github.com/jquery/jquery/issues

**Comment by dmethvin** [comment]
Most likely the discussion in https://github.com/jquery/jquery-migrate/issues/83#issuecomment-95962655 applies. If you have overridden the content type using `dataType: "json"`, or the server explicitly says `Content-type: application/x-json` or similar,  then you *must* provide JSON.

**Comment by mgol** [comment]
Ah, that was it. The difference between status 204 and method HEAD (because we allow empty responses with `content-type: application/json` etc.) is that HEAD is defined to specify `content-type` of the data that would be sent for GET request at the same URL: https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.4
>  The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request.

There is no such demand for responses with status 204 so it seems reasonable to expect `content-type` shouldn't be set to `application/json` when body is empty.

**Comment by senseysensor** [comment]
> There is no such demand for responses with status 204 so it seems reasonable to expect content-type shouldn't be set to application/json when body is empty.

well, I see your point. But let's look from backend point of view: I provide JSON (or we may suppose XML or any other) API. And I don't want mix together JSON and any other content types in my responses. Also client explicitly passes `Accept: application/json` header (because if client passes, for instance, `Accept: text/html`, he will get another response based on his preference – I had such functionality in my previous project). If client requests _application/json_ and server cannot respond with this content type, technically server should return 406 error (Not Acceptable).

And one more point. HTTP specification doesn't tell anything about we cannot use `application/json` with 204 status code. Instead it says, as I mentioned above, that we cannot have any body in the response.

**Comment by mgol** [comment]
As I understand it, the HTTP spec says `content-type` should match the type of the body sent. So if you send no body, even if that's mandated by the status code used, you shouldn't set an incompatible `content-type`. HEAD is different as it's specified in plain letters that it should send `content-type` of the equivalent GET request.

**Comment by dmethvin** [comment]
If flask is returning a 204 response it should not be setting the `Content-type` header. If it is, jQuery still lets you work around that by setting `dataType: "text"` and parsing the JSON yourself with one line of code.

**Comment by senseysensor** [comment]
ok, not set `Content-type` header seems to be good solution. I think issue may be closed.
