### ISSUE TITLE
Bower distribution

### ISSUE THREAD

**Issue by furlanrapha** [jquery/jquery-migrate#227]
Hi,

I know that bower have the version `jquery-migrate-official` but I wasn't able to find the `jquery-migrate.js` and `jquery-migrate.min.js` files.

I need to build with `npm run build` just to get the files?

Best regards,
Furlan

**Comment by dmethvin** [comment]
Every blog post about a release usually has information on how to get the file through bower.
http://blog.jquery.com/2016/05/19/jquery-migrate-1-4-1-released-and-the-path-to-jquery-3-0/

Also the first Google search result for "jquery migrate bower" leads to a ticket with the same info:
https://github.com/jquery/jquery-migrate/issues/43
