### ISSUE TITLE
Warn and fill event shorthands

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-migrate#230]
Core ref https://github.com/jquery/jquery/issues/3214
Docs ref https://github.com/jquery/api.jquery.com/issues/972

**Comment by lpd-au** [comment]
May I ask, why is this a warning in migrate 3? It's really irritating when trying to move from jQuery 2.x -> 3.x and the console is flooded with logs pertaining to 4+/never removals. Surely it can at least be an info/debug line so it's possible to filter out. The task isn't even closed and it's marked 3.3.0, which is yet to be released.

**Comment by mgol** [comment]
@lpd-au `3.3.0` is released now. Migrate's job is to make people give up deprecated features in favor of recommended ones. If they do it, they're much better prepared for the next major release.

In DevTools you can often filter console messages, e.g. in Chrome you can put "-shorthand" in the filter box and you won't see those messages; you can focus on other ones then.
