### ISSUE TITLE
Stop console.logging by default

### ISSUE THREAD

**Issue by corysimmons** [jquery/jquery-migrate#240]
https://wordpress.stackexchange.com/questions/224661/annoying-jqmigrate-migrate-is-in-console-after-update-to-wp-4-5

Fresh installs of WP have a `console.log` from this plugin.

Can we disable that by default? What is the purpose of this?

**Comment by mgol** [comment]
We added this on purpose: #149. You can read about the reasoning in https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-migrate-is-installed-version-x.

People have been including jQuery Migrate by default to increase compatibility with older jQuery plugins and just kept it there constantly. That goes against the Migrate main goal - to *temporarily* allow older code to work, fix all the deprecations and remove Migrate. From the linked `warnings.md`:

> The use jQuery Migrate in production has performance impacts and can complicate debugging as it modifies the normal behavior of the version of jQuery being used.

Migrate, to make new jQuery work with older code, has to modify jQuery behavior, creating a Frankenstein part-new, part-old jQuery. This can create its own problems so we decided it's better to urge people to not leave it like that and get rid of the console.log by fixing deprecations & removing Migrate.

**Comment by corysimmons** [comment]
I see your point.

I also see why Automattic includes it in WP by default, and don't expect plugins that haven't been updated in 5 years to suddenly get updated.

It'd be nice if Automattic forked this project and remove the warning.

Thanks for the explanation.

**Comment by akamustang** [comment]
Anyone know of a fork that removes this message that is kept reasonably up to date?
