### ISSUE TITLE
Uncaught TypeError on jQuery.data() with an object as a second argument

### ISSUE THREAD

**Issue by andrzej-aa** [jquery/jquery-migrate#242]
I'm trying to migrate an Angular application to jQuery@3 but jQuery Migrate breaks the code with `Uncaught TypeError: string.replace is not a function`. Example code is `$.data($('#test').get(0), {a: 1});`. Here is a code snippet https://jsfiddle.net/Ltswm0v6/ It works when I remove jQuery Migrate script https://jsfiddle.net/Ltswm0v6/1/

**Comment by dmethvin** [comment]
This is a dup of #198 and we did decide to support this undocumented API. The fix is in master but not released yet.
