### ISSUE TITLE
Provide option to silence "migrate is installed" message

### ISSUE THREAD

**Issue by tbrisker** [jquery/jquery-migrate#244]
When running our test suite, `JQMIGRATE: Migrate is installed with logging active, version 3.0.0` is printed for every test run (rails integration tests with poltergeist & phantomjs).
Currently the only workaround I found is to temporarily set `window.console = false` before requiring it and restoring it afterwards.

**Comment by mgol** [comment]
A duplicate of #240. Please see there fir the reasoning.
