### ISSUE TITLE
Warn about jQuery.nodeName removal

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery-migrate#246]
See https://github.com/jquery/jquery/issues/3475. To be removed in 4.0.

**Comment by dmethvin** [comment]
This can't be implemented until core refactors to eliminate internal calls to jQuery.nodeName. Otherwise it will throw warnings even if there are no uses in user code.

**Comment by Krinkle** [comment]
Internal callers have been fixed in https://github.com/jquery/jquery/commit/ac9e3016645078e1e42120822cfb2076151c8cbe and released in 3.2.0.

**Comment by dmethvin** [comment]
Right but in general we have said that jQuery Migrate 3.x works with jQuery 3.x. If you used an older jQuery than 3.2 it would be throwing warnings frequently. Is that considered okay? In the past we tried to avoid that.

**Comment by dmethvin** [comment]
It also complicates our test matrix since we couldn't test Migrate 3.2 with a jQuery older than 3.2 and assert no warnings.

**Comment by Krinkle** [comment]
@dmethvin No, I agree 3.x/3.x should be kept. It's our responsibility to keep that flexibility supported to reduce user confusion and upgrade smoothness. If we do want to add the warnings before Migrate 4, it would have to involve a version check.
