### ISSUE TITLE
jQuery 1.5.2 with jquery-migrate-1.4.1.js throws jQuery.attrHooks is undefined

### ISSUE THREAD

**Issue by valpatsk** [jquery/jquery-migrate#252]
Hi.  We are going to migrate from jQuery 1.5.2. 
Using jquery-migrate-1.4.1.js gives us the error "TypeError: jQuery.attrHooks is undefined" in firefox console 
and 
"Uncaught TypeError: Cannot read property 'value' of undefined
    at jquery-migrate-1.4.1.js:89
    at jquery-migrate-1.4.1.js:752" in Chrome console.

Here is the example. The jquery file is taken from CDN
https://jsfiddle.net/Lw5jdjvp/

Thanks!

**Comment by dmethvin** [comment]
The oldest version of jQuery supported by Migrate is 1.6. Try switching to that version of jQuery and use Migrate. You can look at the blog post to see if any 1.6 changes affect you. https://blog.jquery.com/2011/05/03/jquery-16-released/

**Comment by valpatsk** [comment]
Thanks!
