### ISSUE TITLE
Minor release for improved warnings and fixes

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery-migrate#254]
Would be nice if a new minor release could be cut so that the improved warnings from dc1d703f7747d71f (#204) goes out.

----

The minor release from current master would contain:

* Build: add UMD support. #206
* Core: Warn on use of `jQuery.holdReady()`. #247
* **Core: Don't use `.apply()` on `console.log` to satisfy IE9.** #241
* **Data: Fix support object as second argument.** #235
* **Docs: Clarify wording around deprecated/removed methods.** #208
* **Effects: Fix for old style easing definitions compatibility.** #234
* Effects: Warn on use of `jQuery.fx.interval`. #216
* **Event: Warn and fill `jQuery.event.props.concat` for jQuery Mobile pre-1.5**. #209
* Event: Warn about late use of `$(window).on("load"...)`. #217
* Event: Use window.document to get to document. 9e3dfcbf
* Event: Warn for deprecated event aliases. #243

**Comment by dmethvin** [comment]
Yeah, a 3.2 release seems like a good idea. See #220 for why isArray isn't being warned. It's a major pain to do those warnings when there are internal uses inside jQuery itself.  The positional selectors one would be really annoying since they're frequently used and I'm not sure we're ever going to remove them.

**Comment by mgol** [comment]
I think we should warn only in jQuery 3.2.0+ then, better than nothing!

**Comment by Krinkle** [comment]
From <https://github.com/jquery/jquery-migrate/issues/246#issuecomment-287883124>

**Comment by Krinkle** [comment]
@dmethvin Added a release note draft to the start comment. Is anything still blocking a minor release?

**Comment by dmethvin** [comment]
Sorry @Krinkle, I'm not sure exactly what needs to be done at the moment. I need a day to go through and see where things stand. If we're going to catch all the jQuery 3.2.0 deprecations I think there are a few things left and some may not have issues yet, but that would be part of the review.

**Comment by Krinkle** [comment]
@dmethvin If we can get all jQuery 3.2.0 additions finalised soon, that'd be great. But if not, I'd like to consider not blocking on that, and perhaps have a release with a 3.0.x or 3.1.x version number first, to get these fixes released soon?

**Comment by dmethvin** [comment]
SGTM, we can do another release later.
