### ISSUE TITLE
Warn about jquery.load(function(){})

### ISSUE THREAD

**Issue by jeffg2k** [jquery/jquery-migrate#256]
Suggest a warning for  jquery.load(function(){}) to change it to jquery.on("load", function(){}).

I deployed an application after passing jquery-migrate and it failed to catch this migration issue.

**Comment by dmethvin** [comment]
There's already a warning for that plus several tests:

https://github.com/jquery/jquery-migrate/blob/e967c3b98bf0077e4577d4ec05258a7e0b5063e0/src/event.js#L61

https://github.com/jquery/jquery-migrate/blob/e967c3b98bf0077e4577d4ec05258a7e0b5063e0/test/event.js#L19-L53

https://github.com/jquery/jquery-migrate/blob/e967c3b98bf0077e4577d4ec05258a7e0b5063e0/test/event.js#L182-L189

Can you submit a test case? Maybe we missed something.

**Comment by jeffg2k** [comment]
Ah, the git version works.  I was using the jquery-migrate linked on the main site. https://code.jquery.com/jquery-migrate-3.0.0.min.js

Time to update the link or make a new release.

**Comment by jeffg2k** [comment]
Though I guess my problem may have been that that logic that calls the load only runs in certain instances.  I thought the migrate would parse through all the javascript and warn regardless if it executed it.  But that doesn't appear to be the case as adding a if (false) {} around it stopped the warning message.

**Comment by jeffg2k** [comment]
I also had the problem that the load command was not part of the normal operation of the program.  It only ran when a new token is needed, thus it was not tested.  I didn't realize it only warned on executed code.
