### ISSUE TITLE
.selector (removed in 3.0) is not restored in jquery-migrate 3.0.0

### ISSUE THREAD

**Issue by lan9** [jquery/jquery-migrate#259]
https://api.jquery.com/selector/ was removed in 3.0 but the behavior is not restored by jquery-migrate 3.0.0

It seems the supported was added in https://github.com/jquery/jquery-migrate/commit/683b9b3ae40e3fe9e83f3dd39d8e5e958975f3fa, but was removed in https://github.com/jquery/jquery-migrate/pull/155/commits. The latter meant to 'Remove workarounds for APIs dropped before 3.0', but as described in https://api.jquery.com/selector/  `.selector` method is dropped in 3.0, not before 3.0.

**Comment by Krinkle** [comment]
I believe the reason this was removed is because, while it was removed in 3.0, it has been deprecated since 1.7.

**Comment by timmywil** [comment]
Right, as the jQuery README states, first upgrade to 1.12 using [jQuery Migrate 1.x](https://github.com/jquery/jquery-migrate/tree/1.x-stable#readme), then use jQuery-migrate 3.0 to upgrade to jQuery 3.x.
