### ISSUE TITLE
Uncaught TypeError: jQuery.event.addProp is not a function

### ISSUE THREAD

**Issue by aimfeld** [jquery/jquery-migrate#266]
When using jquery-migrate 3.0.0, I get a javascript error that may be caused by a bug in jquery migrate itself:
```
jquery-migrate-3.0.0.js:363 Uncaught TypeError: jQuery.event.addProp is not a function
```
This happens e.g. when clicking on my bootstrap nav tabs, but also when clicking on a simple html select element. When using jquery-migrate 1.4.1, the problem disappears.

See also https://stackoverflow.com/a/37791711/94289

**Comment by mgol** [comment]
Migrate 3 requires jQuery 3.

**Comment by aimfeld** [comment]
@mgol I am using jQuery 3.2.1

**Comment by dmethvin** [comment]
Most likely some combination of Bootstrap, other plugins, jQuery, and jQuery Migrate is conflicting but there's no way to help given the information provided. Do you have a simple test case?

**Comment by aimfeld** [comment]
@dmethvin I can't provide a test case, but here are my frontend dependencies from `packages.json`:
```
{
    "name": "blueprint",
    "version": "1.1.0",
    "private": true,
    "dependencies": {
        "bootstrap-sass": "^3.3.7",
        "bootstrap-slider": "^9.8.1",
        "del": "^3.0.0",
        "gulp": "^3.9.1",
        "gulp-concat": "^2.6.1",
        "gulp-cssnano": "^2.1.2",
        "gulp-gzip": "^1.4.0",
        "gulp-rename": "^1.2.2",
        "gulp-sourcemaps": "^2.6.0",
        "gulp-uglify": "^3.0.0",
        "gulp-util": "^3.0.8",
        "jquery": "^3.2.1",
        "modernizr": "^3.5.0",
        "pickadate": "^3.5.6",
        "sticky-table-headers": "^0.1.19"
    }
}
```
I'm glad to provide more info if needed.

**Comment by aimfeld** [comment]
I suspect jquery-migrate 3 may not play well with `"bootstrap-sass": "^3.3.7",`, since the error occurs on pages where only bootstrap is used and none of the other frontend dependencies.

**Comment by dmethvin** [comment]
Migrate isn't on the dependency list? In any case we can't help without a test case that demonstrates the problem.

**Comment by aimfeld** [comment]
@dmethvin No, since migrate is only used temporarily, I load it directly in the html document using `<script type="text/javascript" src="https://code.jquery.com/jquery-migrate-3.0.0.js"></script>`
It's not a show stopper for me, I downgraded to migrate 1.4.1 which seems to work fine for me.
