### ISSUE TITLE
Cannot pass an object into html function as could be done with jQuery 1.8

### ISSUE THREAD

**Issue by sbrem00** [jquery/jquery-migrate#274]
In jQuery 1.8 it was possible to pass an object into the html() function. After v 1.9 this does not seem to be possible and jQuery migrate does not fix this. Would it be possible to add this to the migrate plugin? 

Here is an example: 
```
$('<div>').html(
    $('div').html('This is a div in a div');
)
```
I know the same result can be achieved in multiple ways but i have come across legacy code that does it this way and would really like to use the migrate plugin.

**Comment by dmethvin** [comment]
Since that was never a documented feature it's not something Migrate would generally support. If you wanted to create a PR that supported it though I'd definitely consider it!
