### ISSUE TITLE
jQuery.fx.interval is deprecated message coming from jQuery.fn.animate when using jquery 3.2.1

### ISSUE THREAD

**Issue by stof** [jquery/jquery-migrate#276]
Using jQuery 3.2.1 and Migrate 3.0.1, I get the `jQuery.fx.interval is deprecated` message in my console. The *only* place using `fx.interval` in my whole codebase is jQuery itself.

**Comment by dmethvin** [comment]
I cannot reproduce this. https://jsfiddle.net/owph9d4q/

If some code actually does touch `jQuery.fx.interval` it gives a stack trace. Where does your stack trace say this is being touched? https://jsfiddle.net/386vqLye/1/

**Comment by stof** [comment]
hmm, I cannot see it anymore today either in my project. Might have been something weird going one. So I'm closing this issue.
