### ISSUE TITLE
Create a jquery "wrapper" to use in the easy NPM migrations

### ISSUE THREAD

**Issue by nyurik** [jquery/jquery-migrate#277]
I would like to propose an alternative usage to `<script src="https://code.jquery.com/jquery-migrate-3.0.1.js"></script>`:   Make jquery-migrate npm package that appears to be identical to jquery.  This way, I don't need to change any `require('jquery')` or webpack settings in a complex project, but only change the package.json:

```yaml
{
  "dependencies": {
    // this could be a link to a .gz NPM package file, etc
    "jquery": "git+https://github.com/jquery/jquery-migrate.git"
  }
}
```

An (yarn-only) alternative is to use package aliasing, https://twitter.com/sebmck/status/873958247304232961?lang=en -- too bad NPM doesn't support it.

**Comment by dmethvin** [comment]
I get uncomfortable with approaches that make it easy to (accidentally or on purpose) do things we don't recommend. Migrate is intended as a debugging/migration tool, it's not even guaranteed to fix all the things that change between releases. It shouldn't be used in a production setup. 

If you find that it's needed in production it might be better to use an older jQuery until you can get dependencies to accept PRs to fix their issues. With npm/yarn you wouldn't even think of forcing incompatible modules to work with each other, which is what is happening here when you include jQuery+Migrate and some plugin not intended for the later version of jQuery.

**Comment by nyurik** [comment]
@dmethvin I understand your concern, and I think we should try to help users not to shoot themselves in the foot if possible. jquery-migrate should never be used in production. My suggestion was purely for testing. The problem is that if you have a very large complicated code base with complex build scripts, injecting `jquery-migrate` right after `jquery` may require thorough knowledge of that codebase and build steps, and in some cases might be too complex to modify.  In these cases, people might simply bump the jquery version and go through the rounds of testing, hoping they will catch all bugs.  Having an alternative testing route will greatly help in these testing scenarios.

We cannot make people follow instructions, or not do stupid things.  In this case, it feels we are sacrificing ease of testing for the hypothetical idiot who will misuse it. The problem is - someone could misuse it no matter how many defenses we put in place.

**Comment by dmethvin** [comment]
So specifically would this only expose the most recent version of jQuery with the most recent version of Migrate? For example, it would be its own `jquery-with-migrate` package. How would that package be versioned?

**Comment by nyurik** [comment]
The `git+https` link can actually link to any revision -- see https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by dmethvin** [comment]
Right, but where would that dependency go? The `package.json` file for `jquery-with-migrate` right? So the version of `jquery-with-migrate` would need to lock itself to a specific jquery version, correct? Is that the way you anticipate it working? When would a new version of `jquery-with-migrate` be released, when either package was updated? Just trying to understand how the interaction would work between the two packages.

**Comment by dmethvin** [comment]
I'm closing this for now but can reopen if a workable approach can be proposed.
