### ISSUE TITLE
Selector with '#' doesn't work

### ISSUE THREAD

**Issue by IevgenRagulin** [jquery/jquery-migrate#279]
This is probably related to https://github.com/jquery/jquery/issues/2824

jQuery("#Курси") selector works. However, when I click on a link that has href set to "Курси", chrome (or some wordpress plugin, javascript library, not sure) automatically URL encodes it, and such a selector doesn't work:

jQuery("#%D0%9A%D1%83%D1%80%D1%81%D0%B8")

And I get an error: Uncaught Error: Syntax error, unrecognized expression: #%D0%9A%D1%83%D1%80%D1%81%D0%B8

I'm using jquery 1.12.4, jquery migrate 1.4.1, Chrome 63

**Comment by dmethvin** [comment]
Since only Migrate 3 is being supported, I'll close this. StackOverflow might be able to help but it would be good to create a test case.
