### ISSUE TITLE
Property "selector" is not restored on the jQuery object for compatibility with jQuery 2

### ISSUE THREAD

**Issue by prantlf** [jquery/jquery-migrate#284]
The property [`selector`](http://api.jquery.com/selector/) was deprecated in jQuery 1.7 and removed in jQuery 3.0.

When the jQuery object is constructed with jQuery 2.2.4:

```js
$el = $('body')
```

It carries the original string selector in the property `selector`:

```js
$el.selector === 'body'
```

When the jQuery object is constructed with jQuery 3.0.0 or 3.2.1, the original selector is not present:

```js
$el.selector === undefined
```
The old implementation of `jQuery()` and `jQuery.fn.find` sets the `selector` property on the returned object:

```js
jQuery.fn.extend( {
	find: function( selector ) {
		var i,
			len = this.length,
			ret = [],
			self = this;

		if ( typeof selector !== "string" ) {
			return this.pushStack( jQuery( selector ).filter( function() {
				for ( i = 0; i < len; i++ ) {
					if ( jQuery.contains( self[ i ], this ) ) {
						return true;
					}
				}
			} ) );
		}

		for ( i = 0; i < len; i++ ) {
			jQuery.find( selector, self[ i ], ret );
		}

		// Needed because $( selector, context ) becomes $( context ).find( selector )
		ret = this.pushStack( len > 1 ? jQuery.unique( ret ) : ret );
		ret.selector = this.selector ? this.selector + " " + selector : selector;
		return ret;
	},
```

The new implementation doesn't need and doesn't set it any more:

```js
jQuery.fn.extend( {
	find: function( selector ) {
		var i, ret,
			len = this.length,
			self = this;

		if ( typeof selector !== "string" ) {
			return this.pushStack( jQuery( selector ).filter( function() {
				for ( i = 0; i < len; i++ ) {
					if ( jQuery.contains( self[ i ], this ) ) {
						return true;
					}
				}
			} ) );
		}

		ret = this.pushStack( [] );

		for ( i = 0; i < len; i++ ) {
			jQuery.find( selector, self[ i ], ret );
		}

		return len > 1 ? jQuery.uniqueSort( ret ) : ret;
	},
```

If some code written with jQuery 2.x depended on the `selector` property, upgrading to jQuery 3.x will break it. Concretely, this affects [Backbone.Marionette](https://github.com/marionettejs/backbone.marionette) 2.x, including the most recent 2.x release -  2.4.7. The method `reset` from `marionette.Region`:

```js
    reset: function() {
      this.empty();
  
      if (this.$el) {
        this.el = this.$el.selector;
      }
  
      delete this.$el;
      return this;
    }
```

The most recent Marionette 3.x release [fixed the problem](https://github.com/marionettejs/backbone.marionette/issues/2668) by storing the original property in their own object and not depending on this jQuery behaviour any more. However, Marionette 3.x is a different major version release, because it changes the interface a lot.

The implication of the problem in Marionette 2.x is severe - re-re-rendering of a `Marionette.LayoutView` will throw an error and the view will remain empty:

```
Error: An "el" undefined must exist in DOM
    at constructor._ensureElement (http://localhost:8888/src/lib/marionette.js?:1238:17)
    at constructor.show (http://localhost:8888/src/lib/marionette.js?:1092:17)
    at BreadcrumbsPanelView.onRender (http://localhost:8888/src/controls/breadcrumbspanel/breadcrumbspanel.view.js?:86:29)
    at Object._triggerMethod (http://localhost:8888/src/lib/marionette.js?:688:25)
    at BreadcrumbsPanelView.triggerMethod (http://localhost:8888/src/lib/marionette.js?:1984:28)
    at BreadcrumbsPanelView.render (http://localhost:8888/src/lib/marionette.js?:2134:12)
    at BreadcrumbsPanelView.render (http://localhost:8888/src/lib/marionette.js?:3140:51)
    at executeBound (http://localhost:8888/src/lib/underscore.js?:734:67)
    at BreadcrumbsPanelView.<anonymous> (http://localhost:8888/src/lib/underscore.js?:747:14)
    at BreadcrumbsPanelView.render (http://localhost:8888/src/lib/underscore.js?:122:29)
```

There can be other applications depending on the existence of the `selector` property.

* Do you agree, that jQuery Migrate plugin should help applications, which depend on the `selector` property, to run, detect the issue and fix it, as long as they use jQuery Migrate plugin?
* Would you accept a PR restoring the property getter and setter with a warning?

**Comment by dmethvin** [comment]
It's a little late? The `.selector` property has been [deprecated since 1.7 which was released in November 2011](https://api.jquery.com/selector/) so it's been documented for a while. The [1.9 upgrade guide from January 2013](https://jquery.com/upgrade-guide/1.9/#selector-property-on-jquery-objects) also made it clear that this was deprecated and that Migrate didn't attempt to fill it. If it was filled, it would have been in the 1.x version of Migrate (which handled warnings and deprecations for both jQuery 1.x and 2.x).  We no longer maintain that version and haven't done a release since 1.4.1 in May 2016.

In general, it should be possible to rewrite any use of the `.selector` property by changing `$(selector).methodUsingSelector(options)` to `$.methodUsingSelector(selector, options)` since it's not using the collection and only the selector string. Can you just do a patch to that effect inside Marionette? We haven't received any other requests for this so it seems to be rare.

**Comment by prantlf** [comment]
Thank you for the quick answer! Yes, I can patch Marionette, because I was able find the problem in my development environment. I was more concerned about other developers, who integrate our code, and who may encounter other problems caused by the same issue... If I could prevent it in the "source" - in jQuery - no errors would be thrown and the compatibility fixing would go on without blocking issues like unhandled errors.

jQuery Migrate 3 is supposed to be used to migrate code, which depends on jQuery 2 today. Do you expect people, who do not use jQuery 1, apply jQuery Migrate 1.9 at first? Having learned, that the `selector` property wasn't covered by jQuery Migrate 1.9, does jQuery Migrate 3 cover all other properties, which were deprecated, when jQuery Migrate 1.9 was released and which were covered there?

My expectation was, that if I apply jQuery Migrate, my application would not break with unhandled errors on the console. The application would run, I would be able to gather the warnings from the console and continue fixing the original code, until the console remained clean. Is your goal to help the developers only with the most often problems, which may not be so easy to discover like an unhandled exceptions?

Would you recommend running an application using jQuery 3 + jQuery Migration 3 in the productive environment at the customer for some time, until all problems are solved? Or would you recommend using jQuery 3 + jQuery Migration 3 in the development environment only, because it will not cover all issues?

If you answer my first question with "we're not restoring all broken jQuery 2 functionality", you will probably answer the last one with "never in productive environment" :-)

**Comment by dmethvin** [comment]
> jQuery Migrate 3 is supposed to be used to migrate code, which depends on jQuery 2 today. Do you expect people, who do not use jQuery 1, apply jQuery Migrate 1.9 at first?

There is a [note at the top of the README.md](https://github.com/jquery/jquery-migrate/blob/master/README.md) that describes the process. It was also described in the [blog entry](https://blog.jquery.com/2016/05/19/jquery-migrate-1-4-1-released-and-the-path-to-jquery-3-0/) introducing jQuery Migrate 3.0. You'd use Migrate 1.x with jQuery 1.x or 2.x, and Migrate 3.x with jQuery 3.x. 

> My expectation was, that if I apply jQuery Migrate, my application would not break with unhandled errors on the console. 

Generally that's true, as long as you use the right Migrate with the right jQuery and note the exceptions in the upgrade guides for [1.9](https://jquery.com/upgrade-guide/1.9/) and [3.0](https://jquery.com/upgrade-guide/3.0/).

You shouldn't really need to include Migrate in production if you've fixed the issues. It's more of a debugging tool. I'd actually recommend against having in in production unless you know it solves a problem you haven't been able to fix.

**Comment by prantlf** [comment]
I see. I misunderstood the [note at the top of the README.md](https://github.com/jquery/jquery-migrate/blob/master/README.md):

> To upgrade to jQuery 3.0, you first need **version 1.12.x or 2.2.x. If you're using an older version**, first upgrade to one of these versions using jQuery Migrate 1.x

I've used jQuery 2.2.4 and not an older version. That's why I didn't even looked for the Migrate 1. Applying Migrate 1 at first and then Migrate 3 makes the upgrade from jQuery 2.2.4 to jQuery 3 a two-step process, which contradicts the goal to run the application in a "compatibility mode" for a short time.

Thank you for your explanations and links! It was helpful, although we need to consider some staged upgrading path.

**Comment by dmethvin** [comment]
Yep, sorry it's not a one-step thing but there are just too many changes to jQuery over time to make it work that way. Contrast that with something like npm which just loads all versions of any module that dependencies might use. You can do something similar using `jQuery.noConflict()` to load multiple versions of jQuery but it's not efficient to do that. Migrate is trying to let you have one version plus some compatibility code but there are limits.

**Comment by prantlf** [comment]
No, using `jQuery.noConflict()` doesn't make the upgrade more efficient. I'd daresay, that it doesn't help at all :-) It would help writing new code with jQuery 3 and leaving the old code intact, if that were the upgrade strategy.

We use RequireJS and mixing of more than one jQuery versions with `jQuery.noConflict()` would work well. However, we use some jQuery plugins and libraries like Backbone, which also depend on jQuery. Introducing a module. Introducing a jQuery3 module would mean in turn introducing Backbone3 and other "*3" modules. jQuery 3 is also a part of the framework and our interface to our partners. It would cause a considerable effort and spread the jQuery upgrade over a long time. Instead of it, we will fix the framework to work with jQuery 3 at first, and then release it as a breaking change. Making a non-breaking upgrade with two jQuery versions may work only for simpler applications.

About `jQuery.noConflict()` - it is valuable, but for other purposes. We develop an embeddable framework with widgets showing information from an ECM system. We use `jQuery.noConflict()` not to affect the global jQuery, which the portal page may be using, where the widgets are integrated.
