### ISSUE TITLE
Property "context" is not restored on the jQuery object for compatibility with jQuery 2

### ISSUE THREAD

**Issue by prantlf** [jquery/jquery-migrate#285]
The property [`context`](http://api.jquery.com/context/) was deprecated in jQuery 1.10 and removed in jQuery 3.0. It is a similar issue to #284 

Are you considering restoring this property with a warning to help the existing applications detecting and fixing this compatibility problem?

**Comment by dmethvin** [comment]
See my comment in #284 . For `context` exactly what are you expecting of that property?

**Comment by prantlf** [comment]
I haven't encountered any problem with this property in our application. We have a big project using dozens of OSS libraries and hundreds of JavaScripts source modules. I haven't tested all of them yet. I noticed the `context` property just next to the `selector` property, when I was looking for the places, where `selector` is set in jQuery.

I think, that the discussion in #284 will resolve this issue too.

**Comment by dmethvin** [comment]
OK we'll continue discussion there.

**Comment by aforian** [comment]
How is the discussion going? Will it be implemented a migration or a warning?
Cause it's wired if an undocumented property `jQuery.cssProps` even has migration and warning at https://github.com/jquery/jquery-migrate/blob/main/src/jquery/css.js#L74C1-L74C1 but the document property [.context](https://api.jquery.com/context/)
