### ISSUE TITLE
Event Shorthand Syntax Doesn't Appear to be Deprecated.

### ISSUE THREAD

**Issue by fletc3her** [jquery/jquery-migrate#288]
I'm running the Migrate 3.0.1 plug-in and seeing a lot of warnings like this (among others):

`Migrate is installed with logging active, version 3.0.1
`
`jQuery.fn.click() event shorthand is deprecated.
`
`jQuery.fn.keypress() event shorthand is deprecated
`
`jQuery.fn.mouseup() event shorthand is deprecated
`

However, there is no indication on the current documentation page for jQuery that this syntax is deprecated. E.g. https://api.jquery.com/click/

Nor does this shorthand appear anywhere in the Deprecated section of the documentation. https://api.jquery.com/category/deprecated/

The best indication I can find is that this syntax is fully supported by the current version of jQuery 3 and that there are no plans to delete this syntax in future versions of jQuery.

jQuery Migrate should not flag code which does not need to be changed. Doing so makes the job of upgrading code to be jQuery 3 compatible look more arduous than it is, encourages people to perform search/replace operations which may introduce errors, and makes it difficult to trust the other recommendations which are made since every recommended change now needs to be cross-referenced against the documentation.

**Comment by dmethvin** [comment]
The methods are deprecated and there is a docs ticket at https://github.com/jquery/api.jquery.com/issues/972 . We'd welcome help in the form of PRs to update the docs.

**Comment by fletc3her** [comment]
Ugh. Upgrading to new versions of jQuery is actually quite easy. Dealing with all the bugs and inconsistencies in Migrate is what is taking all the time. This thing is a fucking joke.

**Comment by fletc3her** [comment]
LOL
