### ISSUE TITLE
outerHeight can return NaN instead of null  since jQuery 3

### ISSUE THREAD

**Issue by oalija** [jquery/jquery-migrate#294]
Since jQuery 3 outerHeight can return NaN, and some sites like drupal views modelue,  plus this returned value with a int calue, and result is NaN not same value as null.

I suggest add this to migrate

```
var oldOuterHeight = jQuery.fn.outerHeight;

jQuery.fn.outerHeight = function() {
    migrateWarn( "jQuery.fn.outerHeight now return NaN instead of null" );

    var value = oldOuterHeight.apply( this, arguments );

    if(isNaN(value)){
        value = null;
    }

    return value;
};
```

**Comment by mgol** [comment]
Can you provide a test case on [JSFiddle](https://jsfiddle.net/) or [JS Bin](https://jsbin.com/)? Thanks!

**Comment by dmethvin** [comment]
Can be reopened with a test case.
