### ISSUE TITLE
Warn about jQuery.cssNumber

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-migrate#296]
See https://github.com/jquery/jquery/issues/4009

Detect assignments to `jQuery.cssNumber` and recommend that it only be done if that property exists; note that it's going away in 4.0.

Recommend that people do not pass raw numbers to `.css()` and instead always pass strings and append `"px"` when appropriate.  Point out `line-height` as a troublesome case.

**Comment by dmethvin** [comment]
Fixed in aee3d06a7468d4749b4fe92e5790956040c17470

**Comment by mgol** [comment]
@dmethvin Where did that commit land? I don't see it on `master`... I was about to submit an issue about filling `cssNumber` and I saw this issue.

**Comment by dmethvin** [comment]
Darned good question! I can't see it either. I'll reopen this to get it into master.

**Comment by dmethvin** [comment]
This can't be landed until internal `cssNumber` usages are removed. I don't think that is going to happen until 4.0.

**Comment by mgol** [comment]
@dmethvin Oh, I see, the linked commit won't work for jQuery 3.x. That said, it seems we could do something else & detect & warn against pushes to `cssNumber`? That way Core code would work.

**Comment by dmethvin** [comment]
Hmmm, sure, we could use a `set` hook [like we did with `jQuery.cssProps`](https://github.com/jquery/jquery-migrate/blob/7b1ff32d3922e535e22ee53dd706acae4c10b0db/src/css.js#L48-L53), I think that should work here as well.

**Comment by mgol** [comment]
Hmm, now that I think about it, pushes to `jQuery.cssNumber` are one thing but passing numbers as values to the `.css()` setter is another and the latter one is most likely way more common. Also, the former one is impossible to detect correctly as we want to keep allowing people to add stuff there, but just to check first if `jQuery.cssNumber` is defined.

Is the issue that Core itself uses numbers as values somewhere? Can you share more details?

**Comment by mgol** [comment]
Hmm, looking closer at the commit removing `cssNumber` (00a9c2e5f4c855382435cec6b3908eb9bd5a53b7) it seems we should change the order of some checks in jQuery 3.x so that `cssNumber` is only checked if you provide a number value. Maybe that would make it feasible to warn on getter access.

**Comment by mgol** [comment]
@dmethvin I think your PR might work with minor modifications. I submitted https://github.com/jquery/jquery/pull/4651 so that it also works with Core `master`.

**Comment by mgol** [comment]
@dmethvin PR: #337.
