### ISSUE TITLE
Make sure the minified file is, in fact, minified

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-migrate#300]
Originally reported at https://github.com/jquery/codeorigin.jquery.com/issues/33 by @buismaarten:
> Hey guys,
>
> Look at this url: http://code.jquery.com/jquery-migrate-3.0.1.min.js
> At the end it says ".min", but the file isn't minified.

**Comment by dmethvin** [comment]
It's minified but still has the original newlines, which we don't do in any of the other jQuery files. It's correct in the 3.0.0.min release, I'll take a look.

**Comment by mgol** [comment]
Yeah, it looks like some minification flags were off.

**Comment by dmethvin** [comment]
We moved from grunt-config-uglify 1.0.1 to 3.0.1. Fortunately it looks like @markelog [just did this for core](https://github.com/jquery/jquery/commit/09684ba3f210594e41ecddf369ac94c688d53ccb) and [it has a bunch of options in that Gruntfile](https://github.com/jquery/jquery/blob/73d7e6259c63ac45f42c6593da8c2796c6ce9281/Gruntfile.js#L248-L281) so I can copy that.

**Comment by georgezee** [comment]
@dmethvin - is there an extra step that needs to be done so that the 3.0.1.min.js can have the new settings applied to it? It still looks to have all the newlines. 
Or will this only take effect from 3.0.2 onwards?

**Comment by mgol** [comment]
@georgezee We can't change the files of already released versions so this will be fixed only starting with the next version of Migrate.

**Comment by georgezee** [comment]
Ok sure - @mgol - thanks for clarifying.
