### ISSUE TITLE
JQMIGRATE: jQuery.fn.on() is deprecated

### ISSUE THREAD

**Issue by kevinhq** [jquery/jquery-migrate#305]
Migrating to jQuery 3.3.1 from jQuery 1.12.4, and I got that warning: JQMIGRATE: jQuery.fn.on() is deprecated

However, I can't find it anywhere, even on Google no one mentioned about it.

The plugin I used is downloaded from there: https://code.jquery.com/jquery-migrate-3.0.1.js

Am I missing something?

**Comment by dmethvin** [comment]
We need to see a test case. You can see the source code, there is no message of that type anywhere. This seems highly unlikely so I'll close the issue, but if you can report a test case we can reopen.

**Comment by kevinhq** [comment]
@dmethvin - sorry, my silly mistake. You were right. 

The cause: I replace all .bind() on the codes, and mistakenly replace the one on this plugin too..
