### ISSUE TITLE
How to build with console warnings disabled?

### ISSUE THREAD

**Issue by OrangeDog** [jquery/jquery-migrate#312]
How do you build the production version from the npm package?

In particular, I'm using webpack 4.
It's not the standard `process.env.NODE_ENV` variable.

**Comment by mgol** [comment]
Thanks for the report. How would you suggest us to handle it? The requirements are that both `dist/jquery-migrate.js` & `dist/jquery-migrate.min.js` must work when included in a script tag in a browse and that `require('jquery-migrate')` works as well. We'd also want to avoid completely separate files for Node & the browser as we don't have a good testing story for that.

We're open to PRs, especially that in Migrate we don't care that much about size (which we do in jQuery itself).

**Comment by dmethvin** [comment]
Since there hasn't been any activity on this ticket I'll assume the reporter got the info they needed.
