### ISSUE TITLE
Warnings on short versions of event binding

### ISSUE THREAD

**Issue by fabianfrz** [jquery/jquery-migrate#313]
Currently the methods like click dblclick etc. throw a warning so I started to migrate them to the on syntax.
However the official jQuery doc does not mention a deprecation.
You can find our developer discussion in this pull request:

opnsense/core#2929

Please clarify which one is wrong. For example:

* https://api.jquery.com/click/
* https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated

I have seen this one: jquery/api.jquery.com#972 and from this list I guess it should be already deprecated (planned for 3.3)

**Comment by dmethvin** [comment]
I agree, the shorthand methods should be marked deprecated in the API docs. There's a ticket there that just needs a PR to match. Are you interested? https://github.com/jquery/api.jquery.com/issues/972

**Comment by dmethvin** [comment]
Closing this ticket since only the docs need to be updated.
