### ISSUE TITLE
extend the jQuery object causes some warnings

### ISSUE THREAD

**Issue by boyandim** [jquery/jquery-migrate#316]
In my case I need to extend the jQuery object to a different object. In such cases the jQuery migrate script shows warnings in the console. I tried to isolate the scenario in really simply [https://dojo.telerik.com/ADAYuqom/2](https://dojo.telerik.com/ADAYuqom/2) example that have only jQuery 3.3.1 script and the jQuery migrate 3.0.1 script.

**Comment by mgol** [comment]
Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) or [CodePen](https://codepen.io/mgol/pen/wNWJbZ) as the issue template requested? Thanks!

**Comment by boyandim** [comment]
Please refer to the [https://jsbin.com/morusihoje/1/edit?html,css,js,console,output](https://jsbin.com/morusihoje/1/edit?html,css,js,console,output) example where the issue can be observed. In the console there are a few warnings caused due to the usage of the extend method for extending the jQuery object.

**Comment by mgol** [comment]
Thanks. This happens because a deep extend needs to access all the fields, even the deprecated ones.

Why would you extend a jQuery object like that, though? What you'll get is not identical to the original object and it's highly likely the object you'd get won't behave in a sensible way. Using jQuery like that is not supported.

**Comment by dmethvin** [comment]
This seems like a super edge case. Yes, if you reference every property on `$` with jQuery Migrate in place it may generate warnings.

**Comment by dmethvin** [comment]
Just reviewing tickets for an upcoming release and wanted to mention that it seems like the desire to "copy" a jQuery object may be similar to the now-deprecated [`jQuery.sub()`](https://api.jquery.com/jQuery.sub/) functionality. As far as I know, most people (including me today reading the docs) were confused by it, almost nobody used it, and we got no complaints when removing it.  If you just want a "fresh" copy of a jQuery collection in an object you can use `$(some_jquery_collection)` to make one.
