### ISSUE TITLE
jQuery 3.4.1 is out

### ISSUE THREAD

**Issue by Franckybleu** [jquery/jquery-migrate#318]
Hello :-)
https://github.com/jquery/jquery/tree/3.4.1
It would be necessary to add the version 3.4.1 as it was done for version 3.4.0
https://github.com/jquery/jquery-migrate/commit/5eafc17bc259c7673fa2878da37ed917e2d825f9

**Comment by dmethvin** [comment]
I'm thinking it would be best to add this, fix anything that may turn up from that, and do a release with a correctly minified file as 3.1.0. We can add the newer 3.x deprecations in a 3.2.0 after that.  /cc @mgol

**Comment by mgol** [comment]
@dmethvin I agree with this plan.
