### ISSUE TITLE
Why `offset` is restored to return `{ left: 0, top: 0}` in 3.1.0?

### ISSUE THREAD

**Issue by panlina** [jquery/jquery-migrate#330]
jQuery 2.2.4 is already returning `undefined` for an empty collection. Why jquery-migrate 3.1.0 is restoring it to return `{ left: 0, top: 0 }`?

https://github.com/jquery/jquery-migrate/blob/3.1.0/src/offset.js

**Comment by dmethvin** [comment]
As the note at the top of the README says, use jQuery Migrate 1.x with either jQuery 1.x or 2.x. 

I agree though that the empty-collection case seems like it should return `undefined`. It also returns `undefined` in jQuery 3.4.0 and in general we return `undefined` for getters on empty collections.

**Comment by panlina** [comment]
We're currently using jQuery 2.2.4, and is upgrading to 3.4.1, so we don't need jQuery Migrate 1.x, and jQuery Migrate 3.1 will patch jQuery 3.x to restore some jQuery 2.2.x behaviors as I understand, so my expectation is with jQuery Migrate 3.1 present `offset()` will return `undefined` for an empty collection as jQuery 2.2.4 does.

Am I understanding correctly?

**Comment by dmethvin** [comment]
Sorry, I know it can be confusing. If there is a better way to explain it in the README please do submit a PR and we'll try to clarify. 

To upgrade in your case, add the latest Migrate 1.x into your existing page that has jQuery 2.x. It will tell you about things that are different, deprecated, or removed in 3.x. Once you've fixed anything that it reports, you can remove jQuery Migrate 1.x and switch your page to the latest jQuery 3.x. It should work at that point.

We're working on jQuery 4 and that is what jQuery Migrate 3 is for. When paired with a jQuery 3 version, it will tell you about things that are being changed for the jQuery 4 release. 

There is a [console warning](https://github.com/jquery/jquery-migrate/blob/master/src/migrate.js#L12-L18) that should have appeared when you tried using jQuery 2 with Migrate 3. Did that show up?

As to `.offset()`, yes, I agree it should be returning `undefined` there.

**Comment by mgol** [comment]
@dmethvin I think the note at the top of Migrate README:

> NOTE: To upgrade to jQuery 3.0, you first need version 1.12.x or 2.2.x. If you're using an older version, first upgrade to one of these versions using [jQuery Migrate 1.x](https://github.com/jquery/jquery-migrate/tree/1.x-stable#readme), to resolve any compatibility issues. For more information about the changes made in jQuery 3.0, see the [upgrade guide](https://jquery.com/upgrade-guide/3.0/) and [blog post](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/).

does seem to suggest using Migrate 3.x with jQuery 1.12.x or 2.2.x is correct. Maybe we could just document the sets of jQuery version + a corresponding compatible Migrate one, perhaps in a table?

**Comment by panlina** [comment]
@dmethvin I have to admit it's really confusing then.

> add the latest Migrate 1.x into your existing page that has jQuery 2.x.

Isn't Migrate 1.x for 1.x-to-2.x migration? [1.x README](https://github.com/jquery/jquery-migrate/blob/1.4.1/README.md) said `Migrate older jQuery code to jQuery 1.9+` in title. Why are you saying it's for migration to 3.x?

And the same, [3.1.0 README](https://github.com/jquery/jquery-migrate/blob/3.1.0/README.md) literally gives the example:

```
<script src="https://code.jquery.com/jquery-3.0.0.js"></script>
<script src="https://code.jquery.com/jquery-migrate-3.1.0.js"></script>
```

which makes me believe I'm using it right.

**Comment by panlina** [comment]
Despite that confusion, will you change `offset` to return `undefined` or leave it?

By the way, seems Migrate 3.1.0 is not patching all breaking changes. It's patching [this breaking change of `offset`](https://jquery.com/upgrade-guide/3.0/#breaking-change-invalid-input-to-the-offset-method), but not other breaking changes like [those of dimension related functions](https://jquery.com/upgrade-guide/3.0/#breaking-change-width-height-css-quot-width-quot-and-css-quot-height-quot-can-return-non-integer-values).

**Comment by mgol** [comment]
@panlina There's no 1.x to 2.x migration needed as the 1.x line maintained API compatibility with the 2.x line. 1.10 was API-equivalent to 2.0, 1.11 to 2.1 & 1.12 to 2.2. Migrate 1.x was originally meant to upgrade older 1.x/2.x versions to newer 1.x/2.x but it shouldn't matter whether it was 1.x or 2.x specifically.

@dmethvin The note at https://jquery.com/download/#jquery-migrate-plugin says:

> The first [Migrate version, i.e. 1.x] will help you update your pre-1.9 jQuery code to jQuery 1.9 up to 3.0.

and then:

> The second version helps you update code to run on jQuery 3.0 or higher, once you have used Migrate 1.x and upgraded to jQuery 1.9 or higher

This does seem a bit unclear.

**Comment by mgol** [comment]
> Despite that confusion, will you change `offset` to return `undefined` or leave it?

Dave already accepted this is a good proposal. Now someone needs to do it, though, so we can't promise any timelines. If you care about it enough to want it available sooner, we welcome PRs!

> By the way, seems Migrate 3.1.0 is not patching all breaking changes. It's patching [this breaking change of `offset`](https://jquery.com/upgrade-guide/3.0/#breaking-change-invalid-input-to-the-offset-method), but not other breaking changes like [those of dimension related functions](https://jquery.com/upgrade-guide/3.0/#breaking-change-width-height-css-quot-width-quot-and-css-quot-height-quot-can-return-non-integer-values).

Can you submit a separate issue about each breaking change that's not covered? It will be easier to track. If you wanted to submit a PR for some of them, that would be great as well (issues should come first, though).

**Comment by panlina** [comment]
I didn't know the relationship between 1.x and 2.x before. Thanks for the explanation. Regarding `offset`, I'll try to work on a PR. I've already patched it myself in our project though.
