### ISSUE TITLE
.selector is undefined (deprecated)

### ISSUE THREAD

**Issue by nivs1978** [jquery/jquery-migrate#342]
I am upgrading from 2.2.4 to 3.5 and the migrate tool does not tell me that the .selector property is deprecated. I know it was deprecated in 1.9 but it still worked in 2.2.4.
So please add a warning if you use .selector property.

To resolve the selector missing I did this:
var buttonSelector = "savebutton";
var button =$(buttonSelector);

then instead of using:
button.selector
I just use:
buttonSelector
E.g.:
$(buttonSelector + '[data-id=" + id + '"]').remove();

**Comment by mgol** [comment]
Thanks for the report.

While Migrate tries to warn against all deprecated usages, sometimes it's not possible. In this case, the selector property is read inside of jQuery so if a warning was added, it would have too many false positives.

Also, @dmethvin, do we still maintain Migrate 1.x or just 3.x?

**Comment by dmethvin** [comment]
We haven't put out a new Migrate 1.x for almost 4 years so I'd call it done. In a situation like Migrate 3.x where we can remove something in core before deprecating, it's possible for us to know that any other usages are coming from outside core. I don't see a simple way to do that retroactively for jQuery 1.x/2.x and Migrate 1.x anyway, even if we were continuing to enhance it.

**Comment by mgol** [comment]
Yeah, it makes sense to me then to only support Migrate 3.x at this point. Let's close this then.
