### ISSUE TITLE
onchange function not working with jquery-2.2.4 and jquery-migrate-plugin-1.4.1

### ISSUE THREAD

**Issue by lufeilong** [jquery/jquery-migrate#347]
The onchange function not working with jquery & jquery migrate plugin, but it works well after remove the jquery migrate plugin.

```
$(document).on('click', '.btn-group .btn', function() {
  var $input = $(this).find('input');
  if($input.is('*[type=radio]')) {
    $('input[name="'+$input.attr('name')+'"]').removeAttr('checked');
    $input.attr('checked','checked');
  }
});
```

```
$(document).on('change', '*', function(e) {
  if(getEvent(e).executeIds) {
    jsfPostAndReRender({
      source: this,
      event: e,
      type: e.type,
      show: jqId(getId($(this))),
      execute: getEvent(e).executeIds,
      render: getEvent(e).renderIds
    });      
    e.stopPropagation();      
    return false;
  }
});
```

**Comment by mgol** [comment]
Thanks for the report. However, Migrate 1.4 [is no longer maintained](https://github.com/jquery/jquery-migrate/issues/342#issuecomment-616191227).

**Comment by dmethvin** [comment]
Also read through the upgrade guide. Migrate can't find everything but the guide can help you identify issues, for example that code snippet above is affected by https://jquery.com/upgrade-guide/1.9/#attr-versus-prop- .
