### ISSUE TITLE
fadeTo() reported as using deprecated API

### ISSUE THREAD

**Issue by bazineta** [jquery/jquery-migrate#360]
```
jquery-migrate.js:100 JQMIGRATE: Use of number-typed values is deprecated in jQuery.fn.css
jquery-migrate.js:102 console.trace
migrateWarn	@	jquery-migrate.js:102
jQuery.fn.css	@	jquery-migrate.js:479
fadeTo	@	jquery.js:7746
```
In this instance, JQM seems to be reporting that jQuery itself is using a deprecated API, specifically, the use of `opacity: 0` in the `fadeTo()` implementation, i.e., the `0` should be a string, not a number.

Checking to see if this is a false positive, as it seems odd that jQuery itself would be using a deprecated API.

**Comment by mgol** [comment]
Thanks for the report!

This is a valid remark. Thankfully, this is already fixed in #348 and it’ll be included in the next Migrate release.
