### ISSUE TITLE
JQuery Migrate Tool is not showing warnings for use of pseudo selectors when they have been deprecated.

### ISSUE THREAD

**Issue by fsereno** [jquery/jquery-migrate#364]
I am trying to upgrade to the latest 3.5.1 version of JQuery with the 3.3.0 migration tool, but it is not showing any warnings for the following breaking changes to selectors :

https://api.jquery.com/category/deprecated/deprecated-3.4/

for example $(".element:first") should be showing a warning according to the deprecated documentation but this is working well and with no errors or warnings.

Many thanks

**Comment by mgol** [comment]
Thanks for the report. However, this is a duplicate of #125.
