### ISSUE TITLE
('#cc_number').validateCreditCard(function(result)     {         alert('CC type: ' + result.card_type.name           + '\nLength validation: ' + result.length_valid           + '\nLuhn validation: ' + result.luhn_valid);     });

### ISSUE THREAD

**Issue by Nutza974** [jquery/jquery-migrate#399]
('#5404321000284506).validateCreditCard(function(result)
    {
        alert('CC type: ' + result.card_type.nattaphong
          + '\nLength validation: ' + result.length_valid
          + '\nLuhn validation: ' + result.luhn_valid);
    });

**Comment by mgol** [comment]
This doesn't look like a bug report...
