### ISSUE TITLE
我

### ISSUE THREAD

**Issue by loveover98** [jquery/jquery-migrate#400]
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

**Comment by mgol** [comment]
Please don't post spam issues.
