### ISSUE TITLE
upgrade Jquery-1.11.2 to directly 3.5.1

### ISSUE THREAD

**Issue by vikasNew** [jquery/jquery-migrate#403]
Hi,

I am using Jquery-1.11.2 version & i want upgrade it to Jquery-3.5.1 using Jquery-Migrate.

can i directly use Jquery-3.5.1 with Jquery-Migrate-3.3.0 in a single step  & start fixing issues by looking into console ?

or do i need to upgrade my Jquery-1.11.2 version to Jquery-1.12.4 with Jquery-Migrate-1.4.1 in first step & In second step i have to upgrade Jquery-1.12.4 version to Jquery-3.5.1 with Jquery-Migrate-3.3.0 in second step.

Thanks in anticipation.

**Comment by mgol** [comment]
Officially, as described at https://blog.jquery.com/2016/05/19/jquery-migrate-1-4-1-released-and-the-path-to-jquery-3-0/, you should update to 1.12.4 or 2.2.4 first. That said, 1.12 is backwards compatible with 1.11 so what you'd like to do will most likely work fine as well.
