### ISSUE TITLE
jQuery.fn.css throws error when an object is used as the name, and number as the value

### ISSUE THREAD

**Issue by mweichert** [jquery/jquery-migrate#404]
jQuery Migrate will treat the name as a string when a number is provided as the value. However, it shouldn't make that assumption.

jQuery UI Slider will make a call to jQuery.fn.css like so:
```
jQuery.css({left: "100%"}, 300);
```

It does this when the animate setting is specified. See https://jsfiddle.net/mweichert/784kjmoh/17/

**Comment by mgol** [comment]
Thanks for the report. However, your code sample has a syntax error. Can you edit your post to fix it?

**Comment by mweichert** [comment]
Updated. Thanks @mgol.

**Comment by mgol** [comment]
`jQuery.css` is a private API, do you mean the [`css` method](https://api.jquery.com/css/)? The object signature [only accepts a single parameter](https://api.jquery.com/css/#css-properties).

It seems what jQuery UI is doing it chooses between `css` and `animate` methods but calls the chosen one with two parameters. The second parameter will be ignored if `css` is chosen but that trips Migrate.

**Comment by mweichert** [comment]
@mgol 

> jQuery.css is a private API, do you mean the css method? 

Yes, the CSS method, which jquery-migrate overrides.

> It seems what jQuery UI is doing it chooses between css and animate methods but calls the chosen one with two parameters. The second parameter will be ignored if css is chosen but that trips Migrate.

Yep, that's the exact issue here. I should probably create a jQuery UI Slider issue as well, but I think jquery-migrate will be used with jQuery UI 1.12.1 a lot and so I would recommend that jquery-migrate resolve this as well by accepting the PR.

Thanks Michal.
