### ISSUE TITLE
Question - Why do methods like blur, focus, click, etc. generate warnings?

### ISSUE THREAD

**Issue by nestedsoftware** [jquery/jquery-migrate#410]
Hi, I am hoping to get some clarification around why the following code is in the migrate plugin. Looking at the [upgrade guide](https://jquery.com/upgrade-guide/3.0/), I do not see any mention of any of these methods being deprecated. Likewise, they are nor marked as deprecated in the [docs](https://api.jquery.com/click/). 

```javascript
jQuery.each( ( "blur focus focusin focusout resize scroll click dblclick " +
	"mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave " +
	"change select submit keydown keypress keyup contextmenu" ).split( " " ),
	function( _i, name ) {

	// Handle event binding
	jQuery.fn[ name ] = function( data, fn ) {
		migrateWarn( "jQuery.fn." + name + "() event shorthand is deprecated" );
		return arguments.length > 0 ?
			this.on( name, null, data, fn ) :
			this.trigger( name );
	};
} );
```

**Comment by mgol** [comment]
They were deprecated in 3.3.0 so they're not in a 3.0.0 upgrade guide.

See:
https://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/
which links to:
https://github.com/jquery/jquery/issues/3214
and:
https://github.com/jquery/jquery/commit/022b69a44e42684bdd0029dd456bedb3b495cc24

We have a docs ticket at:
https://github.com/jquery/api.jquery.com/issues/972
but it's not done yet (PRs welcome).

**Comment by nestedsoftware** [comment]
Thanks very much for the quick reply - much appreciated. I posted a follow-up question here - just hoping to understand more clearly whether this is something that could be removed in version 4... https://github.com/jquery/api.jquery.com/issues/972#issuecomment-758763303
