### ISSUE TITLE
How and how long i can use old code in my old projects?

### ISSUE THREAD

**Issue by qant** [jquery/jquery-migrate#413]
Hi there! Thank you for great library!
 
Since WordPress 5.6 is force us to update jQuery to 3.* some of jQuery code or plugins is pretty old (not maintained but works) and some times not worth to update right now.

I would like to know: 
HOW i can keep the old code working? 
How long i can keep it like this until i will update it or delete?

As i can understand, i need to just attach jquery-migrate to manage to keep old code working, is this correct way?

How long i can use the jquery-migrate and will this support very old code like for  jQuery 1.2 etc?

Thank you!

**Comment by mgol** [comment]
This is more a question to the WordPress team, some details are available in their blog post:
https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/
I'm not sure but you may also be able to force an older jQuery version if you need it, AFAIK the changes affect the defaults but you can change those defaults.

But I'll reiterate - these are all decisions of the WordPress team and any questions about what's included in which version of WordPress would be better asked to their community.
