### ISSUE TITLE
false positive on click deprecated?

### ISSUE THREAD

**Issue by BackuPs** [jquery/jquery-migrate#414]
Hi

![afbeelding](https://user-images.githubusercontent.com/6078370/107113776-6b861d80-6861-11eb-9081-e4d70a87f495.png)

i have this js code

	$.buttonMenu.defaults = {
		offset: [0, 0],
		layout: '<div/>',
		classes: {
			menu: 'theme-button-menu',
			subMenu: 'theme-button-sub-menu',
			hasSub: 'theme-has-sub',
			separator:'theme-button-menu-separator'
		},
		data: null,
		item: {
			text: '',
			"class": '',
			click: function () {}
		},
		beforeShow: function () {},
		afterShow: function () {},
		beforeHide: function () {},
		afterHide: function () {},
		onReady: function() {}
	};

And i get a click deprecated notification on this part of the code on line 102

		 click: function (event) { item.click.call(this, item, event);	}

The full code of the function throwing the deprecation message is below.

		var builtItem = function (item) {
				item = $.extend({}, self.settings.item, item);
				if (typeof (item.sub) !== 'undefined') {
					var $sub = $('<ul/>');
					$.each(item.sub, function () {
						builtItem(this).appendTo($sub);
					});

					return $("<li/>", {
						"class": self.settings.classes.hasSub
					}).append($("<a/>", {
						"class": item["class"],
						text: item.text,
						click: function (event) {
							item.click.call(this, item, event);
						}
					})).append($sub);
				} else {
					if(typeof(item.type) !== 'undefined' && item.type == 'separator'){
						return $("<li/>").addClass(self.settings.classes.separator);
					}else{
						return $("<li/>").append($("<a/>", {
							"class": item["class"],
							text: item.text,
							click: function (event) {
								item.click.call(this, item, event);
							}
						}));
					}
				}
			};		 

even if i change the code to this i still get the deprecation message.

						return $("<li/>").append($("<a/>", {
							"class": item["class"],
							text: item.text,
							click: function (event) {
							}
						}));

![afbeelding](https://user-images.githubusercontent.com/6078370/107116037-09cdaf80-6871-11eb-9b5f-0c8b934dcf72.png)

The full code is attached to this in a zip file. 

Why do i get the deprecated message on this? If i turn off jquery migrate the code works just fine. What am i missing here? Is this a false positive?

[buttonMenu.zip](https://github.com/jquery/jquery-migrate/files/5936523/buttonMenu.zip)

**Comment by mgol** [comment]
Yes, this is a deprecated method. See https://github.com/jquery/jquery-migrate/issues/410#issuecomment-758529911

**Comment by BackuPs** [comment]
Hi

This is not a answer to my question.  I know the method is deprecated. But what is wrong with my code that it generates that message?  What is the work around to avoid that message. There is no on('click', function(){})  solution for this pice of code.

My question was. "is this a false positive?

**Comment by dmethvin** [comment]
That code calls the `click` method. the `"click"` in the object you passed to `$("<a />", object)` calls the `text`, and `click` methods. I'm not a fan at all of that usage specifically because it hides that jQuery is calling methods. It can be rewritten as `$("<a />").attr("class", ...).text(...).click(...)` where it's very clear what's happening and why the deprecation notice appears.
