### ISSUE TITLE
Make jquery-migrate available thru Bower

### ISSUE THREAD

**Issue by dananichev** [jquery/jquery-migrate#43]
Bower is a package manager.
Project page https://github.com/bower/bower

Long story short:
1. Register package in Bower's Registry (https://github.com/bower/bower#registering-packages)
2. Make users happy!

Thanks in advance.

**Comment by srsgores** [comment]
For anyone looking to use ``jquery-migrate`` in your bower projects: do the following in your ``bower.json`` file:

```
 "dependencies": {
    ...
    "jquery-migrate": "http://code.jquery.com/jquery-migrate-1.2.1.js"
  },
```

**Comment by piotr-cz** [comment]
Thanks @srsgores

**Comment by NoICE** [comment]
This helped me discover something unusual. If you do this in canjs 2.2.5:

```js
steal('can/model', 'can/map/attributes', function() {
can.Model.extend('HiThere',
// @Static
{
  attributes: {},
  findAll: function() {
    // doesn't matter
  }
},
// @Prototype
{}
)
})
```

It will throw this error and the model is empty, without definitions. Incomplete. Dead.
But I'm giving it the name, static props and prototype props.

The cause of this is the stealing of can/map/attributes, which breaks it completely and causes it to break. It is deprecated, but it's removed from docs but not from canjs package, so I didn't even knew it was deprecated :-D

**Comment by mindej** [comment]
+1

**Comment by irbian** [comment]
You can also install it as npm dependency and make the bower install it from the node_modules folder
