### ISSUE TITLE
request of ECCN code

### ISSUE THREAD

**Issue by Baldizzone** [jquery/jquery-migrate#440]
Hello, 
We are not able to find the ECCN codes for the component indicated below. Can you please help?

-jquery-migrate - jquery/jquery-migrate 3.0.1

**Comment by mgol** [comment]
I assume this is about https://www.bis.doc.gov/index.php/licensing/commerce-control-list-classification/export-control-classification-number-eccn. Why would this be needed? I don't think any jQuery-related project has something like that assigned. cc @dmethvin

**Comment by dmethvin** [comment]
I'm not sure why we would need a code either.
