### ISSUE TITLE
bbGrid and JQuery 3.5.1

### ISSUE THREAD

**Issue by kanang29** [jquery/jquery-migrate#442]
I want to upgrade JQuery from 1.10.2 to JQuery 3.5.1. I have bbGrid version bbGrid.js 0.8.5.

Not all the features of bbGrid works after an upgrade. I have tried using 0.9.1pre but bbgrid is still broken in my application.

Is there any new version that can support JQuery 3.5.1?

I have observed that bbGrid .js uses </> for a tag where as JQuery 3.5.1 expects separate start and end tags e.g: <i> </i> instead of <i/>

please advise.

**Comment by mgol** [comment]
This needs to be fixed on the bbGrid side.

On your end, all you can do is revert the security fix from jQuery 3.5.0. Please read the [jQuery 3.5.0 blog post](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) & the [upgrade guide](https://jquery.com/upgrade-guide/3.5/) for more details.
