### ISSUE TITLE
Warnings.md missing docs for a few warnings

### ISSUE THREAD

**Issue by Tiberriver256** [jquery/jquery-migrate#443]
I received the following warnings but was unable to find recommended fixes within the warnings.md file:

```
jQuery.fn.scroll() event shorthand is deprecated
JSON-to-JSONP auto-promotion is deprecated
```

**Comment by mgol** [comment]
Thanks for the report.

The first one is:
https://github.com/jquery/jquery-migrate/blob/main/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated
Perhaps the message should be more generic.

The second one landed in https://github.com/jquery/jquery-migrate/pull/376 and it seems I forgot to add an entry in `warnings.md`.

**Comment by mgol** [comment]
OK, for the first issue, I'm not sure what can be improved. There are a lot of shorthands for events, listing them all would create a big list so the most common one - click - has been mentioned in the message. The rest are listed in the description of the warning.

As for the second one, I've submitted a PR: #447.
