### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined at HTMLDocument.handler

### ISSUE THREAD

**Issue by gustavopalinka** [jquery/jquery-migrate#448]
I'm upgrading jQuery 1.3 to 3.6 with jQuery Migrate and already done all process, but the in browsers always show up the message:

**Uncaught TypeError: Cannot read property 'apply' of undefined at HTMLDocument.handler** (VM32362 jquery.top.plugins.js:515)

![image](https://user-images.githubusercontent.com/92818141/147488622-9a37dc4b-34b6-440c-ad12-0b90ba97c2db.png)
![image](https://user-images.githubusercontent.com/92818141/147488711-b4908d46-30e6-432e-a09b-6d5c60aff8d3.png)

Any idea as to how to fixed this?
This TypeError is about plugin (jquery-3.6.0.js)

**Comment by mgol** [comment]
From your message, it looks like the issue is caused by an external plugin, you should report it there. Make sure you have a test case first, though; we can’t do much with just a screenshot of an error in minified code.
