### ISSUE TITLE
IE11:  $.browser.msie is undefined

### ISSUE THREAD

**Issue by ajvincent** [jquery/jquery-migrate#48]
IE11 has a different user agent than Internet Explorer versions of the past.  The result is that the jQuery Migrate plugin doesn't correctly recognize IE 11.  $.browser.version works...

**Comment by merbin2012** [comment]
The $.browser will not work after the version jQuery 1.9, so you should use the jQuery-migrate plugin, more details at
http://allinworld99.blogspot.in/2015/05/find-browser-using-jquery.html
