### ISSUE TITLE
CONTRIBUTING.md -> Weekly Status Meetings is outdated

### ISSUE THREAD

**Issue by bobsbeenjamin** [jquery/jquery-migrate#492]
The [weekly-status-meetings](https://github.com/jquery/jquery-migrate/blob/main/CONTRIBUTING.md#weekly-status-meetings) section of CONTRIBUTING.md seems to be outdated. All 3 links lead to stale resources. See the screenshot below.
Also, I'm guessing the [forum-and-irc](https://github.com/jquery/jquery-migrate/blob/main/CONTRIBUTING.md#forum-and-irc) section is outdated, but that's harder to tell for an outsider. **Note**: I was just browsing this repo, and was interested in learning more, which is how I stumbled on this.
![image](https://github.com/jquery/jquery-migrate/assets/3780939/5dec3498-3b1a-4106-9c43-76fb7514256b)

**Comment by mgol** [comment]
PR: #541
