### ISSUE TITLE
type: module breaking webpack compilation

### ISSUE THREAD

**Issue by bazineta** [jquery/jquery-migrate#523]
Post 3.4.1, the top-level `package.json` has been changed to have `type: module`.

Our host environment is ESM as well, and as such we import jquery-migrate. Unfortunately, with the type defined as module, the CommonJS/AMD wrapper is falling through to browser globals when compiled, and we don't have browser globals for anything, jquery included, and thus we're failing at runtime.

Removing `type: module` from the 3.5.0 `package.json` does resolve the issue.

Using webpack 5.93.0, jquery 3.7.1, jquery-migrate 3.5.0. Backing off to 3.4.1 resolves the issue, as that release did not have `type:module` present.

**Comment by mgol** [comment]
Thanks for the report. This regressed in #512 (cc @timmywil, we need to take this into account in projects that don't have separate `*-dist` repos). I wonder if we can just add a simple `package.json` in `dist` [as we have in jQuery](https://github.com/jquery/jquery/blob/1fa8df5dbd5d84cf55882a38eb6e571abd0aa938/dist/package.json):
```json
{
  "type": "commonjs"
}
```

That should resolve your issue; I wonder if there are other breaking consequences of this change, though.

**Comment by mgol** [comment]
BTW, we'd catch this if we had any Node-based or bundler tests. The Node ones are the easiest but Migrate doesn't really support Node.js.

**Comment by mgol** [comment]
PR: #525

**Comment by bazineta** [comment]
Your fixes come faster than my testing :wink:. Adding the described `package.json` in `dist` does indeed resolve the situation in our case.

**Comment by mgol** [comment]
Thanks for confirming!

**Comment by mgol** [comment]
Fixed in jQuery Migrate `3.5.2`.
