### ISSUE TITLE
$.parseJSON(undefined) throws exception

### ISSUE THREAD

**Issue by mtomas-mpm** [jquery/jquery-migrate#556]
In jQuery 1.12.* the expression

`$.parseJSON(undefined) `

returns null, but in jQuery 3.7.4 with jQuery Migrate 3.5.2 throws an exception.

Could we solve the issue with the following code

`migratePatchAndWarnFunc( jQuery, "parseJSON", function() {
	if (arguments.length === 0 || arguments[0] === undefined) {
		return null;
	}
	return JSON.parse.apply( null, arguments );
}, "parseJSON",
"jQuery.parseJSON is deprecated; use JSON.parse" );`

**Comment by mgol** [comment]
That's not true, `jQuery.parseJSON(undefined)` throws even in jQuery 1.12.4. Did you use jQuery Migrate 1.x with it? You should remove it before updating to jQuery 3.x with Migrate 3.x.

**Comment by mtomas-mpm** [comment]
No, I'm using only jquery-migrate-3.5.2. I'll publish two simple samples on jsfiddle:

1. jQuery 1.12.4 + jQuery Migrate 1.4.1: https://jsfiddle.net/drvespa/mqgecwn3/3/
2. jQuery 3.7.1 + jQuery Migrate 3.5.2: https://jsfiddle.net/drvespa/p5b9gmf2/1/

```
$(document).ready(function() {
	console.log($.parseJSON(undefined));
});
```

1. writes null on console
2. throws an exception
