### ISSUE TITLE
Improved .prop() vs .attr() warnings

### ISSUE THREAD

**Issue by carpii** [jquery/jquery-migrate#64]
There are some instances where converting from .attr() to .prop() are valid, but return different data. Id like to see Migrate warnings about this as it wasnt an obvious change

Example: 

When setting 'href' to "#foo", .attr('href") returns '#foo'

but .prop('href') returns 'http://mydomain.com/mypage.php#foo'

This kinda makes sense, but if you have code which was dynamically setting a relative anchor, its easy to miss

**Comment by dmethvin** [comment]
It doesn't seem like there's a need for a code change here, let me know if think otherwise and I can reopen.
