### ISSUE TITLE
[value=] selector is not reflecting the latest value In IE8

### ISSUE THREAD

**Issue by kidneyball** [jquery/jquery-migrate#70]
```
<html>
<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.js"></script>
<input id="input1" value="true" type="hidden"/>
<input id="input2" value="false" type="hidden"/>
<button onclick="test()">Test</button>
<script>
function test() {
	$('input#input1').attr('value',false)
	$('input#input2').attr('value',true)
	console.log($('input[value=false]').get(0).id)
}
</script>
</body>
</html>
```

When you click the Test button on the page, the console outputs `input1` in IE 9 to 11, as expected. But in IE8 the console outputs `input2`. If I remove the jquery-migrate plugin, IE8 will output `input1`.

Even if I set the value attribute on the element directly ( e.g. `document.getElementById('input1').value=false` ), the `'input[value=fase]'` selector could not pick up the right element in IE8.

**Comment by mgol** [comment]
@dmethvin This issue didn't get any reply; should we still do sth about it? Since it's about IE8, certainly not in Migrate 3.0, but what about 1.x?

**Comment by dmethvin** [comment]
Not sure how this one got lost, but since IE8 is basically dead at this point I'm fine with closing the ticket. If someone wants to submit a well-tested patch though we could certainly accept it. @kidneyball sorry for letting this one fall through the cracks!
