### ISSUE TITLE
add AMD support

### ISSUE THREAD

**Issue by CTAPbIuMABP** [jquery/jquery-migrate#72]
please

**Comment by dmethvin** [comment]
Our goal with jQuery Migrate is to provide a tool that helps you diagnose problems in older code and make the changes required to fix them. In that scenario you'd just include this file while doing the transition and then remove it once that work is complete. I can't recommend doing a production build with Migrate and making it a permanent part of your project, although people certainly do it. For that case you can put an AMD wrapper on it yourself.
