### ISSUE TITLE
isResovled() function

### ISSUE THREAD

**Issue by thbaymet** [jquery/jquery-migrate#97]
Hi,

In Jahia 6.6 CMS the jquery version used is v1.6.2. And there is a jquery function isResolved() which is depracated and removed after Jquery 1.8. 

Please see
http://api.jquery.com/deferred.isresolved/

Is this function is added into the migrate library ? If not, it could be added ? 

Good Luck. 
Thanks.

**Comment by dmethvin** [comment]
With #93 in place this should be easy to add.

**Comment by thbaymet** [comment]
Thanks Dave. Do you mean that I can add myself ? I'm not very good at on this point. 
Can someone add it if it doesn't take much time ? 
Thanks very much Dave.

**Comment by dmethvin** [comment]
Well I meant that it should be possible to do pretty easily. I'll leave it open so that it will be done eventually.
