### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by wbinnssmith** [jquery/jquery-migrate#98]
Given that [npm is now recommended for jquery plugins](http://plugins.jquery.com/), it makes sense that jquery-migrate be published to npm to support the myriad of outdated plugins out there.

Ideally a `main` field is added to the package.json here and a `prepublish` step runs the usual build process. A `.npmignore` file could optionally be used to avoid publishing the sources and tests to the registry.

I'd love to submit a PR for the second half -- let me know if you're open. Of course publishing would be up to the jquery project :smile:

Edit: Just realize that `jquery-migrate` will break as-is with most commonjs bundlers and the default export in jquery (which doesn't leak `$` or `jQuery` to the window). A UMD-style wrapper similar to what jquery uses would probably be best. Likewise, I'd love to submit a pr for this too.

**Comment by dmethvin** [comment]
> Just realize that jquery-migrate will break as-is with most commonjs bundlers and the default export in jquery (which doesn't leak $ or jQuery to the window).

We should separate the "Publish to npm" issue from the "Support CJS internally" one. They're not related. 

Clearly right now we need to serve the 80% (probably more like 95%) case where jQuery is a global and no module loader is being used. As long as we don't *break* that case I am fine with handling all the others and would welcome PRs!

**Comment by Atsman** [comment]
Hello,

When do you plan to publish to npm? 

Best regards,
A;eh

**Comment by dmethvin** [comment]
Publishing was added to the release script in e3593e22bf90008f12754b8b8fc91bd5c9d513c3 and we'll be publishing 1.3.0 within the next couple of days.
